describe("eink optimization setting", function()
    setup(function()
        require("commonrequire")
    end)

    it("should be correctly loaded", function()
        G_reader_settings:save("low_pan_rate", true)
        assert.Equals(G_named_settings.low_pan_rate(), true)
    end)
end)
