describe("FileConverter module", function()
  local FileConverter
  setup(function()
    require("commonrequire")
    FileConverter = require("apps/filemanager/filemanagerconverter")
  end)
  it("should show conversion support for Markdown", function()
    assert.is_true(FileConverter:isSupported("/markdown_file.md"))
  end)
  it("should not show conversion support for PDF", function()
    assert.is_false(FileConverter:isSupported("/pdf_file.pdf"))
  end)
  it("should convert Markdown to HTML", function()
    local markdown = [[
# KOReader Quickstart Guide

Welcome to KOreader. You can activate the menu by swiping down from the top of the screen. Clicking outside the menu or swiping up on the menu will discard it. Turning pages can be done either by swiping left and right or by single taps on the left or right side of the screen.

**Main menu**

![Menu](../resources/menu.svg) You can always view this quickstart guide again through *Help* → *Quickstart guide* in the top right menu.

**Settings**

![Settings](../resources/settings.svg) You can change the language and other settings through the gear icon.

------------

Generated by KOReader v2015.11-982-g704d4238.
]]
    local title = "KOReader Quickstart Guide"
    local html_expected = [[<!DOCTYPE html>
<html>
<head>
<title>KOReader Quickstart Guide</title>
</head>
<body>
<h1>KOReader Quickstart Guide</h1>
<p>Welcome to KOreader. You can activate the menu by swiping down from the top of the screen. Clicking outside the menu or swiping up on the menu will discard it. Turning pages can be done either by swiping left and right or by single taps on the left or right side of the screen.</p>
<p><strong>Main menu</strong></p>
<p><img alt="Menu" src="../resources/menu.svg"> You can always view this quickstart guide again through <em>Help</em> → <em>Quickstart guide</em> in the top right menu.</p>
<p><strong>Settings</strong></p>
<p><img alt="Settings" src="../resources/settings.svg"> You can change the language and other settings through the gear icon.</p>
<hr>
<p>Generated by KOReader v2015.11-982-g704d4238.</p>
</body>
</html>]]
    assert.are.same(html_expected, FileConverter:mdToHtml(markdown, title))
  end)

  it(
    "should convert Markdown to HTML with stylesheet and error handling",
    function()
      local markdown = "# Header\nText"
      local title = "Custom Title"
      local stylesheet = "body { color: red; }"
      local html = FileConverter:mdToHtml(markdown, title, stylesheet)
      assert.truthy(html:find("<style>\nbody { color: red; }\n</style>"))
      assert.truthy(html:find("<title>Custom Title</title>"))
    end
  )

  it("should handle _mdFileToHtml with missing and valid files", function()
    assert.is_nil(
      FileConverter:_mdFileToHtml("/non/existent/path/file.md", "title")
    )

    local tmp = os.tmpname() .. ".md"
    local f = io.open(tmp, "w")
    f:write("# Hello from file\nSome content")
    f:close()

    local html = FileConverter:_mdFileToHtml(tmp, "Hello File")
    os.remove(tmp)
    assert.truthy(html:find("<h1>Hello from file</h1>"))
  end)

  it("should showConvertButtons and convert file to HTML (new file)", function()
    local UIManager = require("ui/uimanager")
    local tmp = os.tmpname() .. ".md"
    local f = io.open(tmp, "w")
    f:write("# Convert Test\nContent")
    f:close()

    local refreshed = false
    local dummy_ui = {
      refreshPath = function()
        refreshed = true
      end,
    }

    FileConverter:showConvertButtons(tmp, dummy_ui)
    assert.is_not_nil(FileConverter.convert_dialog)

    -- Trigger button callback for HTML
    local btn_callback = FileConverter.convert_dialog.buttons[1][1].callback
    btn_callback()

    assert.is_true(refreshed)
    local out_file = tmp .. ".html"
    local out_f = io.open(out_file, "r")
    assert.is_not_nil(out_f)
    local out_content = out_f:read("*all")
    out_f:close()
    assert.truthy(out_content:find("<h1>Convert Test</h1>"))

    assert.is_nil(FileConverter.convert_dialog)

    os.remove(tmp)
    os.remove(out_file)
  end)

  it(
    "should showConvertButtons and handle overwrite confirm when HTML already exists",
    function()
      local UIManager = require("ui/uimanager")
      local tmp = os.tmpname() .. ".md"
      local f = io.open(tmp, "w")
      f:write("# Overwrite Test\nContent")
      f:close()

      local out_file = tmp .. ".html"
      local out_f = io.open(out_file, "w")
      out_f:write("old content")
      out_f:close()

      local dummy_ui = {
        refreshPath = function() end,
      }

      FileConverter:showConvertButtons(tmp, dummy_ui)
      local btn_callback = FileConverter.convert_dialog.buttons[1][1].callback

      local shown_widget
      local orig_show = UIManager.show
      UIManager.show = function(self, widget)
        shown_widget = widget
      end

      btn_callback()
      UIManager.show = orig_show

      assert.is_not_nil(shown_widget)
      assert.is_not_nil(shown_widget.ok_callback)
      shown_widget.ok_callback()

      local read_f = io.open(out_file, "r")
      local new_content = read_f:read("*all")
      read_f:close()
      assert.truthy(new_content:find("<h1>Overwrite Test</h1>"))

      FileConverter:cleanup()
      assert.is_nil(FileConverter.convert_dialog)

      os.remove(tmp)
      os.remove(out_file)
    end
  )
end)
