require("commonrequire")
local Parser = require("plugins/calculator.koplugin.formulaparser.formulaparser")

describe("Formulaparser module", function()
    before_each(function()
        Parser.kill() -- clear variables
    end)

    describe("basic arithmetic", function()
        it("should evaluate addition", function()
            assert.are.equal(3, Parser:eval("1+2"))
        end)
        it("should evaluate subtraction", function()
            assert.are.equal(-1, Parser:eval("1-2"))
        end)
        it("should evaluate multiplication", function()
            assert.are.equal(6, Parser:eval("2*3"))
        end)
        it("should evaluate division", function()
            assert.are.equal(2, Parser:eval("6/3"))
        end)
        it("should evaluate modulo", function()
            assert.are.equal(1, Parser:eval("7%3"))
        end)
        it("should evaluate power", function()
            assert.are.equal(8, Parser:eval("2^3"))
        end)
        it("should evaluate factorial", function()
            assert.are.equal(120, Parser:eval("5!"))
        end)
        it("should respect operator precedence", function()
            assert.are.equal(23, Parser:eval("3+4*5"))
        end)
    end)

    describe("functions", function()
        it("should evaluate ld()", function()
            assert.are.equal(10, Parser:eval("ld(1024)"))
        end)
        it("should evaluate sin()", function()
            assert.is_near(1, Parser:eval("sin(pi/2)"), 0.0001)
        end)
        it("should evaluate abs()", function()
            assert.are.equal(5, Parser:eval("abs(-5)"))
        end)
        it("should evaluate sqrt()", function()
            assert.are.equal(2, Parser:eval("sqrt(4)"))
        end)
        it("should evaluate avg()", function()
            assert.are.equal(2, Parser:eval("avg(1,2,3)"))
        end)
        it("should evaluate c2k()", function()
            assert.are.equal(273.15, Parser:eval("c2k(0)"))
        end)
    end)

    describe("comparisons and logic", function()
        it("should evaluate less than", function()
            assert.is_true(Parser:eval("3<4"))
        end)
        it("should evaluate not equal", function()
            assert.is_false(Parser:eval("4!=4"))
        end)
        it("should evaluate logical or", function()
            assert.is_true(Parser:eval("1>2||2<10"))
        end)
        it("should evaluate logical and", function()
            assert.is_true(Parser:eval("1<2&&2<10"))
        end)
        it("should evaluate complex logical expression", function()
            assert.are.equal(7, Parser:eval("1>2||2<10&&7"))
        end)
        it("should evaluate ternary operator", function()
            assert.are.equal(1, Parser:eval("3>4?1:-1"))
            assert.are.equal(-1, Parser:eval("3<4?1:-1"))
        end)
    end)

    describe("variables", function()
        it("should store and retrieve variables with =", function()
            Parser:eval("x=5")
            assert.are.equal(5, Parser:eval("x"))
        end)
        it("should store and retrieve variables with :=", function()
            Parser:eval("x:=5")
            assert.are.equal(5, Parser:eval("x"))
        end)
        it("should evaluate variables stored with = immediately", function()
            Parser:eval("b=2")
            Parser:eval("x=4+b")
            assert.are.equal(6, Parser:eval("x"))
            Parser:eval("b=5")
            assert.are.equal(6, Parser:eval("x")) -- x should still be 6
        end)
        it("should evaluate variables stored with := lazily", function()
            Parser:eval("b=2")
            Parser:eval("x:=4+b")
            assert.are.equal(6, Parser:eval("x"))
            Parser:eval("b=5")
            assert.are.equal(9, Parser:eval("x")) -- x should now be 9
        end)
        it("should handle multiple assignments", function()
            assert.are.equal(4, Parser:eval("x=2,y=4"))
            assert.are.equal(2, Parser:eval("x"))
            assert.are.equal(4, Parser:eval("y"))
        end)
        it("should handle compound assignments", function()
            Parser:eval("x=10")
            assert.are.equal(12, Parser:eval("x+=2"))
            assert.are.equal(10, Parser:eval("x-=2"))
            assert.are.equal(20, Parser:eval("x*=2"))
            assert.are.equal(10, Parser:eval("x/=2"))
            assert.are.equal(1, Parser:eval("x%=3"))
        end)
        it("should return error for undefined variable", function()
            local res, err = Parser:eval("undefined_var")
            assert.is_nil(res)
            assert.are.equal("Variable 'undefined_var' not defined", err)
        end)
    end)

    describe("syntax and parsing", function()
        it("should handle implicit multiplication", function()
            assert.are.equal(15, Parser:eval("3(2+3)"))
            Parser:eval("x=5")
            assert.are.equal(25, Parser:eval("5x"))
        end)
        it("should handle constants", function()
            assert.is_near(math.pi, Parser:eval("pi"), 0.0001)
            assert.is_near(math.exp(1), Parser:eval("e"), 0.0001)
        end)
        it("should handle comments", function()
            assert.are.equal(3, Parser:eval("1+2//comment"))
            assert.are.equal(3, Parser:eval("1+2/*comment*/"))
        end)
        it("should handle unary minus", function()
            assert.are.equal(-1, Parser:eval("1+-2"))
            assert.are.equal(3, Parser:eval("1--2"))
            assert.are.equal(-2, Parser:eval("1*-2"))
        end)
        it("should parse and then evaluate", function()
            local root = Parser:parse("1+x")
            Parser:eval("x=4")
            assert.are.equal(5, Parser:eval(root))
        end)
        it("should return error for incomplete expression", function()
            local res, err = Parser:eval("1+")
            assert.is_nil(res)
            assert.are.equal("Value expected!", err)
        end)
    end)
end)
