describe("menu_order modules", function()
  setup(function()
    require("commonrequire")
  end)

  it("should merge common_menu_order with custom tables", function()
    local common_menu_order = require("ui/elements/common_menu_order")
    assert.is_function(common_menu_order)

    local merged = common_menu_order({
      custom_category = { "item1", "item2" },
    })
    assert.is_table(merged)
    assert.is_table(merged.custom_category)
    assert.is_table(merged.device)
    assert.is_table(merged.navigation)
    assert.is_table(merged.network)
    assert.is_table(merged.help)
    assert.is_table(merged.exit_menu)
    assert.is_table(merged.setting)
    assert.is_table(merged.screen)
    assert.is_table(merged.taps_and_gestures)
    assert.is_table(merged.tools)
    assert.is_table(merged.search)
    assert.is_table(merged.main)
  end)

  it("should generate filemanager_menu_order structure", function()
    local fm_order = require("ui/elements/filemanager_menu_order")
    assert.is_table(fm_order)
    assert.is_table(fm_order["KOMenu:menu_buttons"])
    assert.is_table(fm_order.filemanager_settings)
    assert.is_table(fm_order.plus_menu)
    assert.is_table(fm_order.search)
  end)

  it("should generate reader_menu_order structure", function()
    local reader_order = require("ui/elements/reader_menu_order")
    assert.is_table(reader_order)
    assert.is_table(reader_order["KOMenu:menu_buttons"])
    assert.is_table(reader_order.navi)
    assert.is_table(reader_order.navi_settings)
    assert.is_table(reader_order.typeset)
    assert.is_table(reader_order.filemanager)
    assert.is_table(reader_order.setting)
    assert.is_table(reader_order.screen)
    assert.is_table(reader_order.document)
    assert.is_table(reader_order.taps_and_gestures)
    assert.is_table(reader_order.search)
    assert.is_table(reader_order.search_settings)
    assert.is_table(reader_order.main)
  end)
end)
