do local _={
  {
    [1]="https://ourworldindata.org/atom.xml",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=atom",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://phys.org/rss-feed/",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://awkwardfamilyphotos.com/feed/",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="http://feeds.feedburner.com/CrackedRSS",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="http://syndication.thedailywtf.com/TheDailyWtf",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://www.thehistoryreader.com/feed/",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="http://www.twis.org/feed/",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://www.nasa.gov/rss/dyn/breaking_news.rss",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
  {
    [1]="https://www.space.com/feeds/all",
    filter_element="",
    limit=10,
    download_full_article=true,
    include_images=true,
    enable_filter=false
  },
};return _;end
