-- ./settings.reader.lua
return {
  ["activate_menu"] = "tap",
  ["auto_restore_wifi"] = true,
  ["autodim_starttime_minutes"] = 4,
  ["autoremove_deleted_items_from_history"] = true,
  ["autowarmth_easy_mode"] = true,
  ["bookmarks_items_font_size"] = 19,
  ["bookmarks_items_per_page"] = 14,
  ["calculator_use_init_file"] = "yes",
  ["closed_rotation_mode"] = 2,
  ["collate"] = "access",
  ["copt_b_page_margin"] = 10,
  ["copt_block_rendering_mode"] = 2,
  ["copt_font_gamma"] = 15,
  ["copt_font_size"] = 16,
  ["copt_h_page_margins"] = {
    [1] = 5,
    [2] = 5,
  },
  ["copt_line_spacing"] = 100,
  ["copt_status_line"] = 0,
  ["copt_t_page_margin"] = 10,
  ["coverbrowser_initial_default_setup_done"] = true,
  ["cre_font"] = "Microsoft YaHei",
  ["cre_fonts_recently_selected"] = {
    [1] = "Bookerly Display",
    [2] = "Amazon Ember",
    [3] = "Baskerville",
    [4] = "Bookerly",
    [5] = "Code2000",
    [6] = "Droid Sans Mono",
    [7] = "FreeSans",
    [8] = "FreeSerif",
    [9] = "Futura Medium",
    [10] = "Helvetica Neue LT 65 Kindle Medium",
    [11] = "Microsoft YaHei",
    [12] = "Noto Naskh Arabic",
    [13] = "Noto Sans",
    [14] = "Noto Sans Arabic UI",
    [15] = "Noto Sans Bengali UI",
    [16] = "Noto Sans CJK SC",
    [17] = "Noto Sans Devanagari UI",
    [18] = "Noto Serif",
    [19] = "NotoSansKR",
    [20] = "NotoSerifKR",
    [21] = "OpenDyslexic",
    [22] = "PMN Caecilia LT",
    [23] = "Palatino",
    [24] = "STHeitiTC",
    [25] = "STSongTC",
  },
  ["cre_header_battery"] = 0,
  ["cre_header_clock"] = 0,
  ["cre_header_page_count"] = 0,
  ["cre_header_page_number"] = 0,
  ["cre_header_status_font_size"] = 20,
  ["dev_no_c_blitter"] = false,
  ["disable_kobolight"] = true,
  ["exporter"] = {
    ["html"] = {
      ["enabled"] = false,
    },
    ["joplin"] = {
      ["enabled"] = false,
      ["ip"] = "localhost",
      ["port"] = 41185,
    },
    ["json"] = {
      ["enabled"] = false,
    },
    ["markdown"] = {
      ["formatting_options"] = {
        ["invert"] = "bold",
        ["lighten"] = "italic",
        ["strikeout"] = "strikethrough",
        ["underscore"] = "underline_markdownit",
      },
      ["highlight_formatting"] = true,
    },
    ["myClippings"] = {
      ["enabled"] = true,
    },
    ["readwise"] = {
      ["enabled"] = false,
    },
    ["text"] = {
      ["enabled"] = false,
    },
  },
  ["fallback_font"] = "Noto Sans CJK SC",
  ["filemanagermenu_tab_index"] = 5,
  ["fl_last_level"] = 80,
  ["floating_punctuation"] = 1,
  ["footer"] = {
    ["align"] = "center",
    ["all_at_once"] = true,
    ["battery"] = true,
    ["battery_hide_threshold"] = 100,
    ["book_author"] = false,
    ["book_author_max_width_pct"] = 30,
    ["book_chapter"] = false,
    ["book_chapter_max_width_pct"] = 30,
    ["book_time_to_read"] = false,
    ["book_title"] = false,
    ["book_title_max_width_pct"] = 30,
    ["bookmark_count"] = true,
    ["bottom_horizontal_separator"] = false,
    ["chapter_progress"] = false,
    ["chapter_progress_bar"] = false,
    ["chapter_time_to_read"] = false,
    ["container_bottom_padding"] = 1,
    ["container_height"] = 14,
    ["disable_progress_bar"] = false,
    ["frontlight"] = true,
    ["hide_empty_generators"] = false,
    ["initial_marker"] = false,
    ["item_prefix"] = "icons",
    ["items_separator"] = "bar",
    ["lock_tap"] = true,
    ["mem_usage"] = false,
    ["page_progress"] = true,
    ["page_turning_inverted"] = false,
    ["pages_left"] = false,
    ["pages_left_book"] = false,
    ["pages_left_includes_current_page"] = false,
    ["percentage"] = false,
    ["progress_bar_min_width_pct"] = 5,
    ["progress_bar_position"] = "alongside",
    ["progress_margin"] = false,
    ["progress_margin_width"] = 10,
    ["progress_pct_format"] = "0",
    ["progress_style_thick_height"] = 7,
    ["progress_style_thin"] = false,
    ["progress_style_thin_height"] = 3,
    ["reclaim_height"] = false,
    ["skim_widget_on_hold"] = true,
    ["text_font_bold"] = false,
    ["text_font_size"] = 14,
    ["time"] = true,
    ["toc_markers"] = false,
    ["toc_markers_width"] = 2,
    ["wifi_status"] = true,
  },
  ["full_refresh_count"] = 6,
  ["history_filter"] = "all",
  ["home_dir"] = "/mnt/us/documents",
  ["hyph_alg_default"] = "@algorithm",
  ["hyph_force_algorithmic"] = true,
  ["inertial_scroll"] = false,
  ["keyboard_chinese_pinyin_settings"] = {
    ["show_candi"] = true,
  },
  ["keyboard_layouts"] = {
    [1] = "zh_CN",
    [2] = "en",
  },
  ["kopt_doc_language"] = "chi_sim",
  ["kopt_forced_ocr"] = 0,
  ["kopt_line_spacing"] = 1.2,
  ["kopt_page_margin"] = 0.1,
  ["kopt_page_scroll"] = 0,
  ["kopt_text_wrap"] = 0,
  ["kopt_zoom_mode_genus"] = 3,
  ["kopt_zoom_mode_type"] = 2,
  ["kosync"] = {
    ["auto_sync"] = true,
    ["checksum_method"] = 0,
    ["pages_before_update"] = 5,
    ["sync_backward"] = 1,
    ["sync_forward"] = 2,
  },
  ["low_pan_rate"] = true,
  ["multiswipes_enabled"] = false,
  ["night_mode"] = false,
  ["open_last_menu_show_filename"] = true,
  ["ota_channel"] = "nightly",
  ["ota_server"] = "http://ota.koreader.rocks/",
  ["page_turns_disable_swipe"] = true,
  ["page_turns_disable_tap"] = true,
  ["panel_zoom_enabled"] = {
    ["cbt"] = true,
    ["cbz"] = true,
  },
  ["panel_zoom_fallback_to_text_selection"] = {
    ["pdf"] = true,
  },
  ["plugins_disabled"] = {
    ["autowarmth"] = true,
    ["calibre"] = true,
    ["japanese"] = true,
    ["movetoarchive"] = true,
    ["profiles"] = true,
    ["wallabag"] = true,
  },
  ["quickstart_shown_version"] = 201905000025,
  ["reader_footer_mode"] = 1,
  ["reverse_collate"] = false,
  ["screensaver_delay"] = "disable",
  ["screensaver_dir"] = "/mnt/us/screensaver",
  ["screensaver_hide_fallback_msg"] = false,
  ["screensaver_img_background"] = "black",
  ["screensaver_message"] = "%T %S %A Page %c / %t Battery %b%",
  ["screensaver_message_position"] = "bottom",
  ["screensaver_msg_background"] = "none",
  ["screensaver_rotate_auto_for_best_fit"] = false,
  ["screensaver_show_message"] = true,
  ["screensaver_stretch_images"] = false,
  ["screensaver_type"] = "random_image",
  ["scroll_method"] = "classic",
  ["show_hidden"] = true,
  ["show_unsupported"] = true,
  ["start_with"] = "last",
  ["statistics"] = {
    ["calendar_browse_future_months"] = false,
    ["calendar_nb_book_spans"] = 3,
    ["calendar_show_histogram"] = true,
    ["calendar_start_day_of_week"] = 2,
    ["convert_to_db"] = true,
    ["freeze_finished_books"] = false,
    ["is_enabled"] = true,
    ["max_sec"] = 7200,
    ["min_sec"] = 5,
  },
  ["style_tweaks"] = {
    ["font_family_all_inherit"] = true,
    ["font_size_all_inherit"] = true,
    ["lineheight_all_inherit"] = true,
  },
  ["style_tweaks_in_dispatcher"] = {},
  ["text_lang_default"] = "en",
  ["toc_items_per_page"] = 14,
  ["vocabulary_builder"] = {
    ["enabled"] = true,
  },
  ["wifi_disable_action"] = "leave_on",
  ["wifi_enable_action"] = "turn_on",
  ["wifi_was_on"] = true,
  ["wikipedia_languages"] = {
    [1] = "zh",
    [2] = "en",
  },
}
