describe("Calculator formulaparser and parserhelp unit tests", function()
  local Parser
  local ParserHelp

  setup(function()
    require("commonrequire")
    Parser = require("plugins/calculator.koplugin/formulaparser/formulaparser")
    ParserHelp = require("plugins/calculator.koplugin/formulaparser/parserhelp")
  end)

  before_each(function()
    Parser.kill() -- Reset all variables
    ParserHelp.setAngleRad()
  end)

  describe("Basic Arithmetic and Parsing", function()
    it("should evaluate basic arithmetic and operator precedence", function()
      assert.are.equal(Parser:eval("1+2"), 3)
      assert.are.equal(Parser:eval("10-4"), 6)
      assert.are.equal(Parser:eval("3*4"), 12)
      assert.are.equal(Parser:eval("12/3"), 4)
      assert.are.equal(Parser:eval("10%3"), 1)
      assert.are.equal(Parser:eval("2^3"), 8)
      assert.are.equal(Parser:eval("4!"), 24)
      assert.are.equal(Parser:eval("2+3*4"), 14)
      assert.are.equal(Parser:eval("(2+3)*4"), 20)
      assert.are.equal(Parser:eval("-5+3"), -2)
      assert.are.equal(Parser:eval("+5+3"), 8)
    end)

    it("should handle implicit multiplication and constants", function()
      assert.are.equal(Parser:eval("2(3+4)"), 14)
      assert.is_number(Parser:eval("2pi"))
      assert.is_number(Parser:eval("2π"))
      assert.is_number(Parser:eval("e+1"))
      assert.are.equal(Parser:eval("true"), true)
      assert.are.equal(Parser:eval("false"), false)
    end)

    it("should strip comments and unicode characters", function()
      assert.are.equal(Parser:eval("5+3 // inline comment"), 8)
      assert.are.equal(Parser:eval("5/*block*/+3"), 8)
      assert.are.equal(Parser:eval("5‒2"), 3) -- emdash
      assert.are.equal(Parser:eval("√(16)"), 4) -- sqrt symbol
    end)
  end)

  describe("Math Functions", function()
    it("should evaluate absolute value, rounding and roots", function()
      assert.are.equal(Parser:eval("abs(-42)"), 42)
      assert.are.equal(Parser:eval("floor(3.9)"), 3)
      assert.are.equal(Parser:eval("round(3.6)"), 4)
      assert.are.equal(Parser:eval("round(3.4)"), 3)
      assert.are.equal(Parser:eval("sqrt(25)"), 5)
    end)

    it("should evaluate logarithms and exponentials", function()
      assert.is_near(Parser:eval("exp(1)"), math.exp(1), 0.0001)
      assert.is_near(Parser:eval("ln(e)"), 1, 0.0001)
      assert.is_near(Parser:eval("ld(8)"), 3, 0.0001)
      assert.is_near(Parser:eval("log(100)"), 2, 0.0001)
    end)

    it("should evaluate temperature conversions", function()
      assert.is_near(Parser:eval("c2k(0)"), 273.15, 0.001)
      assert.is_near(Parser:eval("k2c(273.15)"), 0, 0.001)
      assert.is_near(Parser:eval("f2k(32)"), 273.15, 0.001)
      assert.is_near(Parser:eval("k2f(273.15)"), 32, 0.001)
    end)

    it("should evaluate trigonometric functions in rad, deg, and gon", function()
      Parser:eval("setrad()")
      assert.are.equal(Parser:eval("getAngleMode()"), "radiant")
      assert.is_near(Parser:eval("sin(pi/2)"), 1, 0.0001)
      assert.is_near(Parser:eval("cos(0)"), 1, 0.0001)
      assert.is_near(Parser:eval("tan(0)"), 0, 0.0001)
      assert.is_near(Parser:eval("asin(1)"), math.pi / 2, 0.0001)
      assert.is_near(Parser:eval("acos(1)"), 0, 0.0001)
      assert.is_near(Parser:eval("atan(0)"), 0, 0.0001)

      Parser:eval("setdeg()")
      assert.are.equal(Parser:eval("getAngleMode()"), "degree")
      assert.is_near(Parser:eval("sin(90)"), 1, 0.0001)
      assert.is_near(Parser:eval("cos(0)"), 1, 0.0001)
      assert.is_near(Parser:eval("tan(45)"), 1, 0.0001)
      assert.is_near(Parser:eval("asin(1)"), 90, 0.0001)
      assert.is_near(Parser:eval("acos(1)"), 0, 0.0001)
      assert.is_near(Parser:eval("atan(1)"), 45, 0.0001)

      Parser:eval("setgon()")
      assert.are.equal(Parser:eval("getAngleMode()"), "gon")
      assert.is_near(Parser:eval("sin(100)"), 1, 0.0001)
      assert.is_near(Parser:eval("cos(0)"), 1, 0.0001)
    end)

    it("should evaluate statistical and random functions", function()
      assert.are.equal(Parser:eval("avg(2, 4, 6, 8)"), 5)
      Parser:eval("rndseed(42)")
      assert.is_number(Parser:eval("rnd(10)"))
      assert.is_number(Parser:eval("rnd(0)"))
    end)
  end)

  describe("Bitwise and Logical Operators", function()
    it("should evaluate bitwise operations", function()
      assert.are.equal(Parser:eval("5 & 3"), 1)
      assert.are.equal(Parser:eval("5 | 2"), 7)
      assert.are.equal(Parser:eval("5 ~ 3"), 6)
      assert.are.equal(Parser:eval("5 # 3"), -2)
      assert.are.equal(Parser:eval("# 5"), -6)
    end)

    it("should evaluate logical operations", function()
      assert.are.equal(Parser:eval("true && false"), false)
      assert.are.equal(Parser:eval("true || false"), true)
      assert.are.equal(Parser:eval("true ## false"), true)
      assert.are.equal(Parser:eval("## true"), false)
      assert.are.equal(Parser:eval("true ~~ false"), true)
      assert.are.equal(Parser:eval("true ~~ true"), false)
    end)

    it("should evaluate comparisons", function()
      assert.are.equal(Parser:eval("1 < 2"), true)
      assert.are.equal(Parser:eval("2 < 1"), false)
      assert.are.equal(Parser:eval("2 <= 2"), true)
      assert.are.equal(Parser:eval("3 > 2"), true)
      assert.are.equal(Parser:eval("2 >= 2"), true)
      assert.are.equal(Parser:eval("5 == 5"), true)
      assert.are.equal(Parser:eval("5 == 6"), false)
      assert.are.equal(Parser:eval("5 != 6"), true)
      assert.are.equal(Parser:eval("5 != 5"), false)
    end)

    it("should evaluate ternary operator", function()
      assert.are.equal(Parser:eval("1 < 2 ? 10 : 20"), 10)
      assert.are.equal(Parser:eval("1 > 2 ? 10 : 20"), 20)
    end)
  end)

  describe("Variables and Expressions", function()
    it("should support variable assignment, modification, and evaluation", function()
      assert.are.equal(Parser:eval("a = 10"), 10)
      assert.are.equal(Parser:eval("a += 5"), 15)
      assert.are.equal(Parser:eval("a -= 3"), 12)
      assert.are.equal(Parser:eval("a *= 2"), 24)
      assert.are.equal(Parser:eval("a /= 4"), 6)
      assert.are.equal(Parser:eval("a %= 4"), 2)

      -- Expression tree definition
      Parser:eval("b = 2")
      Parser:eval("fn := 4 + b")
      assert.are.equal(Parser:eval("fn"), 6)
      Parser:eval("b = 10")
      assert.are.equal(Parser:eval("fn"), 14)

      -- Sequence operator
      assert.are.equal(Parser:eval("x = 1, y = 2, x + y"), 3)

      -- showvars and kill
      local vars_str = Parser:showvars()
      assert.is_string(vars_str)
      assert.is_true(vars_str:find("b=") ~= nil)

      assert.is_true(Parser.kill("b"))
      assert.is_false(Parser.kill("non_existent_var"))
      assert.is_true(Parser.kill())
    end)

    it("should support greek character conversion and help / bug texts", function()
      assert.is_string(Parser.help())
      assert.is_string(Parser.bug())

      local greek_str = Parser:text2greek("alpha + beta")
      assert.is_string(greek_str)
      local text_str = Parser:greek2text(greek_str)
      assert.is_string(text_str)
      assert.is_true(text_str:find("alpha") ~= nil)
    end)
  end)

  describe("Error Handling and Boundary Conditions", function()
    it("should handle math domain and type errors gracefully", function()
      local res, err = Parser:eval("sqrt(-4)")
      assert.is_false(res)
      assert.is_string(err)

      res, err = Parser:eval("ln(-1)")
      assert.is_false(res)

      res, err = Parser:eval("ld(-2)")
      assert.is_false(res)

      res, err = Parser:eval("log(-10)")
      assert.is_false(res)

      res, err = Parser:eval("abs(true)")
      assert.is_false(res)

      res, err = Parser:eval("5.5 & 2")
      assert.is_false(res)

      res, err = Parser:eval("true + 5")
      assert.is_false(res)

      res, err = Parser:eval("true < 5")
      assert.is_false(res)

      res, err = Parser:eval("5 == true")
      assert.is_false(res)
    end)

    it("should test ParserHelp functions directly for complete coverage", function()
      assert.is_nil(math.finite(nil))
      assert.is_nil(math.finite("abc"))
      assert.is_nil(math.finite(1/0))
      assert.is_true(math.finite(42))
      assert.is_true(math.finite("42"))

      assert.is_nil(ParserHelp.factorial(nil))
      assert.is_nil(ParserHelp.factorial(true))
      assert.is_nil(ParserHelp.factorial(5, 2)) -- err_a_val

      assert.is_nil(ParserHelp.abs(nil))
      assert.is_nil(ParserHelp.acos(nil))
      assert.is_nil(ParserHelp.asin(nil))
      assert.is_nil(ParserHelp.atan(nil))
      assert.is_nil(ParserHelp.cos(nil))
      assert.is_nil(ParserHelp.sin(nil))
      assert.is_nil(ParserHelp.tan(nil))
      assert.is_nil(ParserHelp.exp(nil))
      assert.is_nil(ParserHelp.ln(nil))
      assert.is_nil(ParserHelp.log2(nil))
      assert.is_nil(ParserHelp.log(nil))
      assert.is_nil(ParserHelp.floor(nil))
      assert.is_nil(ParserHelp.round(nil))
      assert.is_nil(ParserHelp.randomseed(true))
      assert.is_nil(ParserHelp.rnd(true))
      assert.is_nil(ParserHelp.sqrt(nil))

      assert.are.equal(ParserHelp.add(nil, 5), 5)
      assert.are.equal(ParserHelp.sub(nil, 5), -5)
      assert.is_nil(ParserHelp.mul(nil, 5))
      assert.is_nil(ParserHelp.div(nil, 5))
      assert.is_nil(ParserHelp.mod(nil, 5))
      assert.is_nil(ParserHelp.pot(nil, 5))

      assert.is_nil(ParserHelp.bitOr(nil, 1))
      assert.is_nil(ParserHelp.bitAnd(nil, 1))
      assert.is_nil(ParserHelp.bitNand(nil, nil))
      assert.is_nil(ParserHelp.bitXor(nil, 1))

      assert.is_nil(ParserHelp.logOr(nil, 1))
      assert.is_nil(ParserHelp.logAnd(nil, 1))
      assert.is_nil(ParserHelp.logNand(nil, nil))
      assert.is_nil(ParserHelp.logXor(nil, 1))
      assert.are.equal(ParserHelp.logNand(nil, true), false)

      assert.is_nil(ParserHelp.lt(nil, 1))
      assert.is_nil(ParserHelp.le(nil, 1))
      assert.is_nil(ParserHelp.gt(nil, 1))
      assert.is_nil(ParserHelp.ge(nil, 1))
      assert.is_nil(ParserHelp.ne(nil, 1))
      assert.is_nil(ParserHelp.eq(nil, 1))

      assert.is_nil(ParserHelp.ternary(nil, 1, 2))
    end)
  end)
end)
