describe("ParserHelp module for Calculator", function()
  local ParserHelp

  setup(function()
    require("commonrequire")
    package.unloadAll()
    require("document/canvascontext"):init(require("device"))

    package.path = "plugins/calculator.koplugin/formulaparser/?.lua;"
      .. package.path
    ParserHelp = require("plugins/calculator.koplugin/formulaparser/parserhelp")
  end)

  after_each(function()
    ParserHelp.setAngleRad()
  end)

  describe("Help text & table exposure", function()
    it("should expose help text and functions table", function()
      assert.is_table(ParserHelp)
      assert.is_string(ParserHelp.help_text)
      assert.is_string(ParserHelp.bug_text)
      assert.is_table(ParserHelp.greek)
      assert.True(#ParserHelp.help_text > 0)
    end)
  end)

  describe("math.finite", function()
    it("should correctly identify finite numbers and non-finite values", function()
      assert.is_nil(math.finite(nil))
      assert.is_true(math.finite("42"))
      assert.is_true(math.finite("-12.34"))
      assert.is_nil(math.finite("abc"))
      assert.is_nil(math.finite({}))
      assert.is_nil(math.finite(math.huge))
      assert.is_nil(math.finite(-math.huge))
      assert.is_nil(math.finite(0 / 0))
      assert.is_true(math.finite(0))
      assert.is_true(math.finite(-3.5))
      assert.is_true(math.finite(1e6))
    end)
  end)

  describe("Angle mode helpers and trigonometric functions", function()
    it("should set and get angle modes accurately", function()
      assert.are.equal(1, ParserHelp.setAngleRad())
      assert.are.equal("radiant", ParserHelp.getAngleMode())

      local deg = ParserHelp.setAngleDeg()
      assert.is_number(deg)
      assert.are.equal("degree", ParserHelp.getAngleMode())

      local gon = ParserHelp.setAngleGon()
      assert.is_number(gon)
      assert.are.equal("gon", ParserHelp.getAngleMode())
    end)

    it("should evaluate sin, cos, and tan in radiant mode", function()
      ParserHelp.setAngleRad()
      assert.are.equal(0, ParserHelp.sin(0))
      assert.are.equal(1, ParserHelp.cos(0))
      assert.is_true(math.abs(ParserHelp.sin(math.pi / 2) - 1) < 1e-10)
      assert.is_true(math.abs(ParserHelp.cos(math.pi / 2)) < 1e-10)
      assert.is_true(math.abs(ParserHelp.tan(math.pi / 4) - 1) < 1e-10)

      -- Negative angle and quadrant reduction
      assert.is_true(math.abs(ParserHelp.sin(-math.pi / 6) - (-0.5)) < 1e-10)
      assert.is_true(math.abs(ParserHelp.cos(-math.pi / 3) - 0.5) < 1e-10)
      assert.is_true(math.abs(ParserHelp.sin(5 * math.pi / 6) - 0.5) < 1e-10)
      assert.is_true(math.abs(ParserHelp.sin(7 * math.pi / 6) - (-0.5)) < 1e-10)
    end)

    it("should evaluate trigonometric functions in degree and gon modes", function()
      ParserHelp.setAngleDeg()
      assert.is_true(math.abs(ParserHelp.sin(90) - 1) < 1e-10)
      assert.is_true(math.abs(ParserHelp.cos(90)) < 1e-10)
      assert.is_true(math.abs(ParserHelp.cos(0) - 1) < 1e-10)
      assert.is_true(math.abs(ParserHelp.sin(30) - 0.5) < 1e-10)
      assert.is_true(math.abs(ParserHelp.asin(1) - 90) < 1e-10)
      assert.is_true(math.abs(ParserHelp.acos(1)) < 1e-10)
      assert.is_true(math.abs(ParserHelp.atan(1) - 45) < 1e-10)

      -- tan at 90 deg returns NaN
      local tan90 = ParserHelp.tan(90)
      assert.is_true(tan90 ~= tan90)

      ParserHelp.setAngleGon()
      assert.is_true(math.abs(ParserHelp.sin(100) - 1) < 1e-10)
      assert.is_true(math.abs(ParserHelp.cos(100)) < 1e-10)
      assert.is_true(math.abs(ParserHelp.atan(1) - 50) < 1e-10)
    end)

    it("should enforce validation on trigonometric arguments", function()
      local val, err = ParserHelp.sin(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      val, err = ParserHelp.cos(true)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      val, err = ParserHelp.tan(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      val, err = ParserHelp.asin(false)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      val, err = ParserHelp.acos(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      val, err = ParserHelp.atan(true)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)
    end)
  end)

  describe("Arithmetic and basic math functions", function()
    it("should handle abs, identity, and sign/addition", function()
      assert.are.equal(5, ParserHelp.abs(-5))
      assert.are.equal(5, ParserHelp.abs(5))
      local val, err = ParserHelp.abs(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.abs(true)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      assert.are.equal(42, ParserHelp.identity(42))
      assert.are.equal(3, ParserHelp.identity(1, 2, 3))

      -- Unary add (sign) and binary add
      assert.are.equal(5, ParserHelp.add(nil, 5))
      assert.are.equal(5, ParserHelp.add(2, 3))
      val, err = ParserHelp.add(nil, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.add(true, 3)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      -- Unary sub (negation) and binary sub
      assert.are.equal(-5, ParserHelp.sub(nil, 5))
      assert.are.equal(5, ParserHelp.sub(7, 2))
      val, err = ParserHelp.sub(5, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.sub(5, false)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)
    end)

    it("should handle mul, div, mod, pot, floor, and round", function()
      assert.are.equal(12, ParserHelp.mul(3, 4))
      local val, err = ParserHelp.mul(nil, 4)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.mul(true, 4)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      assert.are.equal(5, ParserHelp.div(10, 2))
      val, err = ParserHelp.div(10, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(1, ParserHelp.mod(10, 3))
      val, err = ParserHelp.mod(nil, 3)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(8, ParserHelp.pot(2, 3))
      val, err = ParserHelp.pot(2, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(3, ParserHelp.floor(3.7))
      assert.are.equal(-4, ParserHelp.floor(-3.7))
      val, err = ParserHelp.floor(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(3, ParserHelp.round(3.4))
      assert.are.equal(4, ParserHelp.round(3.5))
      assert.are.equal(-3, ParserHelp.round(-3.4))
      val, err = ParserHelp.round(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
    end)

    it("should handle exp, sqrt, and logarithmic functions", function()
      assert.are.equal(1, ParserHelp.exp(0))
      local val, err = ParserHelp.exp(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(4, ParserHelp.sqrt(16))
      assert.are.equal(0, ParserHelp.sqrt(0))
      val, err = ParserHelp.sqrt(-1)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)
      val, err = ParserHelp.sqrt(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.is_true(math.abs(ParserHelp.ln(math.exp(1)) - 1) < 1e-10)
      val, err = ParserHelp.ln(0)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)
      val, err = ParserHelp.ln(-5)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)
      val, err = ParserHelp.ln(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.is_true(math.abs(ParserHelp.log2(8) - 3) < 1e-10)
      val, err = ParserHelp.log2(0)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)

      assert.is_true(math.abs(ParserHelp.log(100) - 2) < 1e-10)
      val, err = ParserHelp.log(-10)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)
    end)

    it("should handle factorial, randomseed, and rnd", function()
      assert.are.equal(120, ParserHelp.factorial(5))
      assert.are.equal(1, ParserHelp.factorial(0))
      assert.are.equal(1, ParserHelp.factorial(1))
      local val, err = ParserHelp.factorial(5, 1)
      assert.is_nil(val)
      assert.are.equal("No value allowed!", err)
      val, err = ParserHelp.factorial(nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.factorial(true)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)
      val, err = ParserHelp.factorial(-5)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)
      val, err = ParserHelp.factorial(3.5)
      assert.is_nil(val)
      assert.are.equal("Domain error!", err)

      assert.is_nil(ParserHelp.randomseed(nil))
      val, err = ParserHelp.randomseed(true)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)
      ParserHelp.randomseed(12345)
      ParserHelp.randomseed(-1)

      assert.is_nil(ParserHelp.rnd(nil))
      val, err = ParserHelp.rnd(false)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)
      local r = ParserHelp.rnd(10)
      assert.is_true(r >= 0 and r <= 10)
      local rf = ParserHelp.rnd(0)
      assert.is_true(rf >= 0 and rf <= 1)
    end)
  end)

  describe("Temperature, sequence, average, and ternary", function()
    it("should convert temperatures between Celsius, Kelvin, and Fahrenheit", function()
      assert.are.equal(273.15, ParserHelp.celsius2kelvin(0))
      assert.are.equal(0, ParserHelp.kelvin2celsius(273.15))
      assert.are.equal(273.15, ParserHelp.fahrenheit2kelvin(32))
      assert.are.equal(32, ParserHelp.kelvin2fahrenheit(273.15))
    end)

    it("should handle seq and avg", function()
      local s = ParserHelp.seq(1, 2, 3, 4, 5)
      assert.is_table(s)
      assert.are.equal(5, #s)
      assert.are.equal(3, s[3])

      assert.are.equal(2.5, ParserHelp.avg(1, 2, 3, 4))
      assert.are.equal(10, ParserHelp.avg(10))
      local avg_val, avg_err = ParserHelp.avg()
      assert.is_nil(avg_val)
      assert.are.equal("Value expected!", avg_err)
    end)

    it("should evaluate ternary operator", function()
      assert.are.equal(10, ParserHelp.ternary(true, 10, 20))
      assert.are.equal(20, ParserHelp.ternary(false, 10, 20))
      local val, err = ParserHelp.ternary(nil, 10, 20)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
    end)
  end)

  describe("Bitwise, logical, and comparison operations", function()
    it("should evaluate bitwise operations and enforce integer checks", function()
      assert.are.equal(7, ParserHelp.bitOr(5, 3))
      local val, err = ParserHelp.bitOr(5.5, 3)
      assert.is_nil(val)
      assert.are.equal("Bitoperations only on integer values!", err)
      val, err = ParserHelp.bitOr(nil, 3)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
      val, err = ParserHelp.bitOr(true, 1)
      assert.is_nil(val)
      assert.are.equal("Arithmetics on boolean?", err)

      assert.are.equal(2, ParserHelp.bitAnd(6, 3))
      val, err = ParserHelp.bitAnd(6, 3.2)
      assert.is_nil(val)
      assert.are.equal("Bitoperations only on integer values!", err)

      -- bitNand: unary bnot(r) when l is nil vs binary
      assert.are.equal(-1, ParserHelp.bitNand(nil, 0))
      local bnot_val = ParserHelp.bitNand(nil, 1)
      assert.are.equal(bit.bnot(1), bnot_val)
      assert.are.equal(bit.bnot(bit.band(5, 3)), ParserHelp.bitNand(5, 3))
      val, err = ParserHelp.bitNand(1.5, 2)
      assert.is_nil(val)
      assert.are.equal("Bitoperations only on integer values!", err)
      val, err = ParserHelp.bitNand(nil, 1.5)
      assert.is_nil(val)
      assert.are.equal("Bitoperations only on integer values!", err)
      val, err = ParserHelp.bitNand(nil, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(6, ParserHelp.bitXor(5, 3))
      val, err = ParserHelp.bitXor(5, 3.1)
      assert.is_nil(val)
      assert.are.equal("Bitoperations only on integer values!", err)
    end)

    it("should evaluate logical operations", function()
      assert.are.equal(true, ParserHelp.logOr(true, false))
      assert.are.equal(false, ParserHelp.logOr(false, false))
      local val, err = ParserHelp.logOr(nil, true)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(false, ParserHelp.logAnd(true, false))
      assert.are.equal(true, ParserHelp.logAnd(true, true))
      val, err = ParserHelp.logAnd(true, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      -- logNand: unary not r when l is nil vs binary
      assert.are.equal(false, ParserHelp.logNand(nil, true))
      assert.are.equal(true, ParserHelp.logNand(nil, false))
      assert.are.equal(false, ParserHelp.logNand(true, true))
      assert.are.equal(true, ParserHelp.logNand(true, false))
      val, err = ParserHelp.logNand(nil, nil)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)

      assert.are.equal(true, ParserHelp.logXor(true, false))
      assert.are.equal(false, ParserHelp.logXor(true, true))
      val, err = ParserHelp.logXor(nil, true)
      assert.is_nil(val)
      assert.are.equal("Value expected!", err)
    end)

    it("should evaluate comparisons and detect type mismatches", function()
      assert.is_true(ParserHelp.lt(2, 5))
      assert.is_false(ParserHelp.lt(5, 2))
      local val, err = ParserHelp.lt(true, 5)
      assert.is_nil(val)
      assert.are.equal("Comparison on boolean?", err)
      assert.is_nil(ParserHelp.lt(nil, 5))

      assert.is_true(ParserHelp.le(2, 2))
      assert.is_false(ParserHelp.le(3, 2))
      val, err = ParserHelp.le(true, false)
      assert.is_nil(val)
      assert.are.equal("Comparison on boolean?", err)

      assert.is_true(ParserHelp.ge(3, 2))
      assert.is_false(ParserHelp.ge(2, 3))
      val, err = ParserHelp.ge(false, true)
      assert.is_nil(val)
      assert.are.equal("Comparison on boolean?", err)

      assert.is_true(ParserHelp.gt(5, 2))
      assert.is_false(ParserHelp.gt(2, 5))
      val, err = ParserHelp.gt(true, 5)
      assert.is_nil(val)
      assert.are.equal("Comparison on boolean?", err)

      assert.is_true(ParserHelp.eq(4, 4))
      assert.is_false(ParserHelp.eq(4, 5))
      val, err = ParserHelp.eq(4, "4")
      assert.is_nil(val)
      assert.are.equal("Mixed comparison!", err)

      assert.is_true(ParserHelp.ne(4, 5))
      assert.is_false(ParserHelp.ne(4, 4))
      val, err = ParserHelp.ne(4, "4")
      assert.is_nil(val)
      assert.are.equal("Mixed comparison!", err)
    end)
  end)
end)
