describe("BatteryState plugin tests #nocov", function()
    local MockTime, module, time

    local stat = function() --luacheck: ignore
        return module:new():stat()
    end

    local function resetAll(widget)
        widget:reset(true, true, true)
        local State = getmetatable(widget.awake_state)
        widget.charging_state = State:new()
        widget.awake_state = State:new()
    end

    setup(function()
        require("commonrequire")
        package.unloadAll()
        require("document/canvascontext"):init(require("device"))
        time = require("ui/time")
        MockTime = require("mock_time")
        MockTime:install()
    end)

    teardown(function()
        MockTime:uninstall()
        package.unloadAll()
        require("document/canvascontext"):init(require("device"))
    end)

    before_each(function()
        local Device = require("device")
        local PowerD = Device:getPowerDevice()
        stub(PowerD, "isCharging")
        PowerD.isCharging.returns(false)
        stub(PowerD, "isCharged")
        PowerD.isCharged.returns(false)

        module = dofile("plugins/batterystat.koplugin/main.lua")
        G_defaults:save("BATTERY_STAT_DO_NOT_RESET", false)
    end)

    after_each(function()
        local Device = require("device")
        local PowerD = Device:getPowerDevice()
        PowerD.isCharging:revert()
        PowerD.isCharged:revert()
    end)

    it("should record charging time", function()
        local widget = stat()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        resetAll(widget)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onCharging()
        assert.are.equal(0, widget.awake.time)
        assert.is_true(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        -- Awake charging time should be reset.
        assert.are.equal(0, widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(time.s(1), widget.charging.time)

        widget:onNotCharging()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        -- awake & discharging time should be reset.
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(time.s(1), widget.charging.time)

        widget:onCharging()
        assert.is_true(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        -- Awake charging time should be reset.
        assert.are.equal(0, widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(time.s(1), widget.charging.time)
    end)

    it("should record suspending time", function()
        local widget = stat()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        resetAll(widget)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onSuspend()
        assert.is_false(widget.was_charging)
        assert.is_true(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(time.s(1), widget.sleeping.time)
        assert.are.equal(time.s(2), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onResume()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(2), widget.awake.time)
        assert.are.equal(time.s(1), widget.sleeping.time)
        assert.are.equal(time.s(3), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onSuspend()
        assert.is_false(widget.was_charging)
        assert.is_true(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(2), widget.awake.time)
        assert.are.equal(time.s(2), widget.sleeping.time)
        assert.are.equal(time.s(4), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)
    end)

    it("should not swap the state when several charging events fired", function()
        local widget = stat()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        resetAll(widget)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onCharging()
        assert.is_true(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        -- Awake charging time should be reset.
        assert.are.equal(0, widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(time.s(1), widget.charging.time)

        widget:onCharging()
        assert.is_true(widget.was_charging)
        assert.is_false(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(0, widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(time.s(2), widget.charging.time)
    end)

    it("should not swap the state when several suspending events fired", function()
        local widget = stat()
        assert.is_false(widget.was_charging)
        assert.is_false(widget.was_suspending)
        resetAll(widget)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(0, widget.sleeping.time)
        assert.are.equal(time.s(1), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onSuspend()
        assert.is_false(widget.was_charging)
        assert.is_true(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(time.s(1), widget.sleeping.time)
        assert.are.equal(time.s(2), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onSuspend()
        assert.is_false(widget.was_charging)
        assert.is_true(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(time.s(2), widget.sleeping.time)
        assert.are.equal(time.s(3), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)

        widget:onSuspend()
        assert.is_false(widget.was_charging)
        assert.is_true(widget.was_suspending)
        MockTime:increase(1)
        widget:accumulate()
        assert.are.equal(time.s(1), widget.awake.time)
        assert.are.equal(time.s(3), widget.sleeping.time)
        assert.are.equal(time.s(4), widget.discharging.time)
        assert.are.equal(0, widget.charging.time)
    end)
end)
