describe("Terminal Aliases plugin module", function()
  local Aliases, lfs, UIManager, ffiUtil
  local saved_ui_show, saved_ui_close
  local shown_widgets, closed_widgets

  setup(function()
    require("commonrequire")
    package.unloadAll()
    require("document/canvascontext"):init(require("device"))

    UIManager = require("ui/uimanager")
    ffiUtil = require("ffi/util")
    lfs = require("libs/libkoreader-lfs")
    Aliases = require("plugins/terminal.koplugin/aliases")
  end)

  before_each(function()
    shown_widgets = {}
    closed_widgets = {}
    saved_ui_show = UIManager.show
    saved_ui_close = UIManager.close
    UIManager.show = function(self_ui, widget)
      table.insert(shown_widgets, widget)
    end
    UIManager.close = function(self_ui, widget)
      table.insert(closed_widgets, widget)
    end
  end)

  after_each(function()
    UIManager.show = saved_ui_show
    UIManager.close = saved_ui_close
  end)

  it("should load alias file entries into kv_pairs and sort alphabetically", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_load_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write("# Comment line\n\n")
    f:write('alias zsh="zsh -l"\n')
    f:write('alias ll="ls -la"\n')
    f:write('alias gs="git status"\n')
    f:close()

    local inst = {
      filename = tmp_file,
      kv_pairs = {},
    }
    setmetatable(inst, { __index = Aliases })

    inst:load()
    assert.is_table(inst.kv_pairs)
    assert.are.equal(5, #inst.kv_pairs) -- Create new, separator, gs, ll, zsh
    assert.are.equal("gs", inst.kv_pairs[3][1])
    assert.are.equal("git status", inst.kv_pairs[3][2])
    assert.are.equal("ll", inst.kv_pairs[4][1])
    assert.are.equal("ls -la", inst.kv_pairs[4][2])
    assert.are.equal("zsh", inst.kv_pairs[5][1])
    assert.are.equal("zsh -l", inst.kv_pairs[5][2])

    os.remove(tmp_file)
  end)

  it("should handle missing alias file gracefully on load", function()
    local inst = {
      filename = "/nonexistent/path/aliases_" .. ffiUtil.getpid() .. ".sh",
      kv_pairs = {},
    }
    setmetatable(inst, { __index = Aliases })

    inst:load()
    assert.are.equal(2, #inst.kv_pairs)
    assert.are.equal("---", inst.kv_pairs[2])
  end)

  it("should save kv_pairs to target alias file atomically", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_save_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write("")
    f:close()

    local inst = {
      filename = tmp_file,
      kv_pairs = {
        { "Create a new alias", "" },
        "---",
        { "gs", "git status" },
        { "ll", "ls -la" },
      },
    }
    setmetatable(inst, { __index = Aliases })

    inst:save()

    local readFile = io.open(tmp_file, "r")
    assert.is_not_nil(readFile)
    local content = readFile:read("*a")
    readFile:close()

    assert.is_not_nil(content:find("# Aliases generated by terminal emulator", 1, true))
    assert.is_not_nil(content:find('alias gs="git status"', 1, true))
    assert.is_not_nil(content:find('alias ll="ls -la"', 1, true))

    os.remove(tmp_file)
  end)

  it("should show InfoMessage when save fails", function()
    local inst = {
      filename = "/nonexistent_dir/forbidden/aliases.sh",
      kv_pairs = {
        { "Create a new alias", "" },
        "---",
        { "ll", "ls -la" },
      },
    }
    setmetatable(inst, { __index = Aliases })

    inst:save()
    assert.are.equal(1, #shown_widgets)
  end)

  it("should show KeyValuePage and handle show and updateKeyValues lifecycle", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_show_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write('alias gs="git status"\n')
    f:close()

    local close_cb = function() end
    local parent_obj = { transmit = function() end }

    local inst = {}
    setmetatable(inst, { __index = Aliases })

    inst:show(tmp_file, close_cb, parent_obj)
    assert.are.equal(tmp_file, inst.filename)
    assert.are.equal(close_cb, inst.close_callback)
    assert.are.equal(parent_obj, inst.parent)
    assert.is_not_nil(inst.alias_kv)
    assert.are.equal(1, #shown_widgets)

    inst:updateKeyValues()
    assert.are.equal(1, #closed_widgets)
    assert.are.equal(2, #shown_widgets)

    os.remove(tmp_file)
  end)

  it("should handle editAlias dialog Cancel button", function()
    local inst = {
      filename = lfs.currentdir() .. "/test_aliases_edit_" .. ffiUtil.getpid() .. ".sh",
      kv_pairs = {
        { "Create a new alias", "" },
        "---",
        { "gs", "git status" },
      },
    }
    setmetatable(inst, { __index = Aliases })

    inst:editAlias("gs", "git status")
    assert.are.equal(1, #shown_widgets)
    local dialog = shown_widgets[1]

    -- Cancel button is buttons[1][1]
    local cancel_btn = dialog.buttons[1][1]
    assert.are.equal("Cancel", cancel_btn.text)
    cancel_btn.callback()
    assert.are.equal(1, #closed_widgets)
  end)

  it("should handle editAlias dialog Delete button", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_del_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write('alias gs="git status"\n')
    f:close()

    local transmitted = {}
    local parent_obj = {
      transmit = function(self_p, cmd)
        table.insert(transmitted, cmd)
      end,
    }

    local inst = {
      filename = tmp_file,
      parent = parent_obj,
      kv_pairs = {
        { "Create a new alias", "" },
        "---",
        { "gs", "git status" },
      },
    }
    setmetatable(inst, { __index = Aliases })
    inst.alias_kv = { kv_pairs = inst.kv_pairs }

    inst:editAlias("gs", "git status")
    local dialog = shown_widgets[1]

    -- Delete button is buttons[1][2]
    local delete_btn = dialog.buttons[1][2]
    assert.are.equal("Delete", delete_btn.text)
    delete_btn.callback()

    assert.are.equal(1, #transmitted)
    assert.are.equal("unalias gs\n", transmitted[1])
    assert.are.equal(2, #inst.kv_pairs) -- only header entries remain

    os.remove(tmp_file)
  end)

  it("should handle editAlias dialog Save button for adding and updating aliases", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_save_btn_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write("")
    f:close()

    local transmitted = {}
    local parent_obj = {
      transmit = function(self_p, cmd)
        table.insert(transmitted, cmd)
      end,
    }

    local inst = {
      filename = tmp_file,
      parent = parent_obj,
      kv_pairs = {
        { "Create a new alias", "" },
        "---",
        { "gs", "git status" },
      },
    }
    setmetatable(inst, { __index = Aliases })
    inst.alias_kv = { kv_pairs = inst.kv_pairs }

    inst:editAlias("gs", "git status")
    local dialog = shown_widgets[1]

    -- Save button is buttons[1][3]
    local save_btn = dialog.buttons[1][3]
    assert.are.equal("Save", save_btn.text)

    -- Mock getFields to update alias to "gs" -> "git status -sb"
    dialog.getFields = function()
      return { "gs", "git status -sb" }
    end
    save_btn.callback()

    assert.are.equal(2, #transmitted)
    assert.are.equal("unalias gs\n", transmitted[1])
    assert.are.equal("alias gs='git status -sb'\n", transmitted[2])
    assert.are.equal("git status -sb", inst.kv_pairs[3][2])

    os.remove(tmp_file)
  end)

  it("should handle editAlias dialog Execute button", function()
    local transmitted = {}
    local parent_obj = {
      transmit = function(self_p, cmd)
        table.insert(transmitted, cmd)
      end,
    }

    local exited = false
    local inst = {
      parent = parent_obj,
      alias_kv = {
        onExit = function() exited = true end,
      },
    }
    setmetatable(inst, { __index = Aliases })

    inst:editAlias("gs", "git status")
    local dialog = shown_widgets[1]

    -- Execute button is buttons[1][4]
    local exec_btn = dialog.buttons[1][4]
    assert.are.equal("Execute", exec_btn.text)

    dialog.getFields = function()
      return { "gs", "git status" }
    end
    exec_btn.callback()

    assert.is_true(exited)
    assert.are.equal(1, #transmitted)
    assert.are.equal("git status\n", transmitted[1])
  end)

  it("should load aliases starting with an underscore", function()
    local tmp_file = lfs.currentdir() .. "/test_aliases_underscore_" .. ffiUtil.getpid() .. ".sh"
    local f = io.open(tmp_file, "w")
    f:write('alias _ll="ls -la"\n')
    f:close()

    local inst = {
      filename = tmp_file,
      kv_pairs = {},
    }
    setmetatable(inst, { __index = Aliases })

    inst:load()

    local found = false
    for i = 3, #inst.kv_pairs do
      if inst.kv_pairs[i][1] == "_ll" then
        found = true
        assert.are.equal("ls -la", inst.kv_pairs[i][2])
        break
      end
    end
    os.remove(tmp_file)

    assert.is_true(found)
  end)
end)
