return require("ui/elements/common_menu_order")({
  ["KOMenu:menu_buttons"] = {
    "navi",
    "typeset",
    "setting",
    "tools",
    "search",
    "filemanager",
    "main",
  },
  navi = {
    "table_of_contents",
    "bookmarks",
    "toggle_bookmark", -- if not Device:isTouchDevice()
    "bookmark_browsing_mode",
    "navi_settings",
    "----------------------------",
    "page_map",
    "hide_nonlinear_flows",
    "----------------------------",
    "book_map", -- if Device:isTouchDevice()
    "page_browser", -- if Device:isTouchDevice()
    "----------------------------",
    "go_to",
    "skim_to",
    "progress_sync",
    "autoturn",
    "----------------------------",
    "go_to_previous_location",
    "go_to_next_location",
  },
  navi_settings = {
    "toc_ticks_level_ignore",
    "----------------------------",
    "toc_items_per_page",
    "toc_items_font_size",
    "toc_items_show_chapter_length",
    "toc_items_with_dots",
    "----------------------------",
    "toc_alt_toc",
    "----------------------------",
    "handmade_toc",
    "handmade_hidden_flows",
    "handmade_settings",
    "----------------------------",
    "bookmarks_settings",
  },
  typeset = {
    "document_settings",
    "----------------------------",
    "set_render_style",
    "style_tweaks",
    "----------------------------",
    "change_font",
    "typography",
    "----------------------------",
    "switch_zoom_mode",
    "----------------------------",
    "page_overlap",
    "speed_reading_module_perception_expander",
    "----------------------------",
    "highlight_options",
    "selection_text", -- if Device:hasDPad()
    "panel_zoom_options",
    "djvu_render_mode",
    "start_content_selection", -- if Device:hasDPad(), put this as last one so it is easy to select with "press" and "up" keys
  },
  setting = {
    -- common settings
    -- those that don't exist will simply be skipped during menu gen
    "frontlight", -- if Device:hasFrontlight()
    "night_mode",
    "----------------------------",
    "network",
    "screen",
    "----------------------------",
    "taps_and_gestures", -- if Device:isTouchDevice()
    "navigation",
    "document",
    "----------------------------",
    "language",
    "device",
    "----------------------------",
    "status_bar",
  },
  document = {
    "document_metadata_location",
    "document_auto_save",
    "document_end_action",
    "language_support",
    "----------------------------",
    "partial_rerendering",
  },
  screen = {
    "screensaver",
    "coverimage",
    "autodim",
    "auto_frontlight",
    "keep_alive",
    "----------------------------",
    "screen_rotation",
    "----------------------------",
    "screen_dpi",
    "screen_eink_opt",
    "autowarmth",
    "color_rendering",
    "----------------------------",
    "screen_timeout",
    "fullscreen",
    "----------------------------",
    "screen_notification",
  },
  taps_and_gestures = {
    "gesture_manager",
    "gesture_intervals",
    "----------------------------",
    "ignore_hold_corners",
    "screen_disable_double_tab",
    "----------------------------",
    "follow_links",
    "----------------------------",
    "menu_activate",
    "page_turns",
    "scrolling",
    "long_press",
  },
  tools = {
    "read_timer",
    "calibre",
    "exporter",
    "statistics",
    "move_to_archive",
    "wallabag",
    "news_downloader",
    "text_editor",
    "profiles",
    "qrclipboard",
    "----------------------------",
    "book_shortcuts",
    "doc_setting_tweak",
    "terminal",
    "----------------------------",
    "plugin_management",
    "patch_management",
    "----------------------------",
    -- For more tools with sorting_hint.
  },
  search = {
    "search_settings",
    "----------------------------",
    "dictionary_lookup",
    "dictionary_lookup_history",
    "vocabbuilder",
    "----------------------------",
    "wikipedia_lookup",
    "wikipedia_history",
    "----------------------------",
    "translate_current_page",
    "----------------------------",
    "find_book_in_calibre_catalog",
    "fulltext_search",
    "fulltext_search_findall_results",
    "bookmark_search",
  },
  search_settings = {
    "dictionary_settings",
    "wikipedia_settings",
    "translation_settings",
    "----------------------------",
    "fulltext_search_settings",
  },
  filemanager = {},
  main = {
    "history",
    "open_previous_document",
    "----------------------------",
    "favorites",
    "collections",
    "----------------------------",
    "book_status",
    "book_info",
    "----------------------------",
    "mass_storage_actions", -- if Device:canToggleMassStorage()
    "----------------------------",
    "common_log_files",
    "ota_update", -- if Device:hasOTAUpdates()
    "help",
    "keyboard_shortcuts", -- explicitly place it here to save key presses
    "----------------------------",
    "exit_menu",
  },
})
