local ffi = require("ffi")

ffi.cdef([[
enum MencaFileStatus_e {
  kMencaNoStatus = 0,
  kMencaInCloud = 1,
  kMencaSyncing = 2,
  kMencaDownloaded = 3,
};
enum bt_service_e {
  BT_UNKNOWN = 0,
  BT_AUTH = 1,
  BT_OBEX = 2,
  BT_SECOND_SCREEN = 3,
};
enum bt_service_state_e {
  BT_SERVICE_ACTIVE = 0,
  BT_SERVICE_CANCEL = 1,
  BT_SERVICE_ERROR = 2,
};
enum obex_status_e {
  OBEX_UNKNOWN = 0,
  OBEX_ERROR = 1,
  OBEX_REQUEST_AUTH = 2,
  OBEX_REQUEST_AUTH_DONE = 3,
  OBEX_TRANSFERRING = 4,
  OBEX_DONE = 5,
};
enum PB_STATE_e {
  MP_STOPPED = 0,
  MP_REQUEST_FOR_PLAY = 1,
  MP_PLAYING = 2,
  MP_PAUSED = 3,
  MP_PREVTRACK = 4,
  MP_NEXTTRACK = 5,
  MP_TRACK_FINISHED = 6,
  MP_LOAD_FILE_AND_PAUSE = 7,
};
enum PB_TTS_STATE_e {
  TTS_STOPPED = 0,
  TTS_PLAYING = 1,
  TTS_PAUSED = 2,
};
enum COVERCACHE_STORAGES_e {
  CCS_NONE = 0,
  CCS_ADOBE = 1,
  CCS_FBREADER = 2,
  CCS_DJVIEWER = 3,
  CCS_MAXSTORAGE = 4,
};
enum input_dev_e {
  UNKNOWN = 0,
  CAPTOUCH = 1,
  DIGITIZER = 2,
  MAX_INPUT_DEV = 3,
};
enum estyle {
  ROUND_ALL = 1,
  ROUND_TOP = 2,
  ROUND_DOWN = 3,
  ROUND_LEFT = 4,
  ROUND_RIGHT = 5,
  ROUND_TOP_LEFT = 6,
  ROUND_TOP_RIGHT = 7,
  ROUND_BOTTOM_LEFT = 8,
  ROUND_BOTTOM_RIGHT = 9,
};
typedef enum {
  SFLAGS_NONE = 0,
  SFLAGS_LEFT = 1,
  SFLAGS_RIGHT = 2,
  SFLAGS_RIGHT_LEFT = 3,
  SFLAGS_UP = 4,
  SFLAGS_UP_LEFT = 5,
  SFLAGS_UP_RIGHT = 6,
  SFLAGS_UP_RIGHT_LEFT = 7,
  SFLAGS_DOWN = 8,
  SFLAGS_DOWN_LEFT = 9,
  SFLAGS_DOWN_RIGHT = 10,
  SFLAGS_DOWN_RIGHT_LEFT = 11,
  SFLAGS_DOWN_UP = 12,
  SFLAGS_DOWN_UP_LEFT = 13,
  SFLAGS_DOWN_UP_RIGHT = 14,
  SFLAGS_ALL = 15,
} SideFlags;
typedef enum {
  PANEL_DISABLED = 0,
  PANEL_ENABLED = 2,
  PANEL_EVENT_NO_HANDLING = 4,
} PANEL_FLAGS;
typedef enum {
  FONT_STD = 0,
  FONT_BOLD = 1,
  FONT_ITALIC = 2,
  FONT_BOLDITALIC = 3,
  FONT_MONO = 4,
} FONT_TYPE;
typedef enum {
  STYLE_UNKNOWN = 0,
  STYLE_KEYBOARD = 1,
  STYLE_TOUCHPANEL = 2,
  STYLE_TOUCHPANEL_KEYBORAD = 3,
  STYLE_MAX_NOT_USED = 4,
} AppStyles;
typedef enum {
  APPLICATION_READER = 0,
  APPLICATION_ATTRIBUTE_MAX = 31,
} APPLICATION_ATTRIBUTE;
typedef enum {
  NET_STATE_UNKNOWN = -1,
  DISCONNECTED = 0,
  CONNECTING = 1,
  CONNECTED = 2,
} NET_STATE;
typedef enum {
  NO = 0,
  WEP = 1,
  WPAEAP = 2,
  WPAPSK = 3,
} WIFI_SECURITY;
typedef struct iv_wlist_s *(*pointer_to_word_hand_t)(int, int, int);
typedef union {
  char intr[8];
  char addr[16];
  char hw_addr[18];
} network_interface;
typedef struct {
  network_interface ip_addr;
  network_interface mask;
  network_interface br_addr;
  network_interface hw_addr;
} network_interface_info;
typedef char proxy_settings;
typedef enum {
  kBTInfo = 0,
  kBTAttention = 1,
  kBTWarning = 2,
  kBTQuestion = 3,
  kBTButton = 4,
} eBubbleTypes;
typedef enum {
  FM_SHOW_SIZE = 1,
} FONT_MENU_FLAGS;
typedef void (*iv_timerproc)();
typedef int (*iv_handler)(int, int, int);
typedef void (*iv_menuhandler)(int);
typedef void (*iv_hashdelproc)(void *);
typedef void (*iv_timerprocEx)(void *);
typedef void (*iv_keyboardhandler)(char *);
typedef void (*iv_dialoghandler)(int);
typedef void (*iv_timeedithandler)(long int);
typedef void (*iv_fontselecthandler)(char *, char *, char *, char *);
typedef void (*iv_dirselecthandler)(char *);
typedef void (*iv_confighandler)();
typedef void (*iv_itemchangehandler)(char *);
typedef void (*iv_pageselecthandler)(int);
typedef void (*iv_bmkhandler)(int, int, long long int);
typedef void (*iv_tochandler)(long long int);
typedef void (*iv_itempaint)(int, int, int, int);
typedef int (*iv_listhandler)(int, int, int, int, int);
typedef void (*iv_rotatehandler)(int);
typedef int (*iv_turnproc)(int);
typedef int (*iv_recurser)(char *, int, void *);
typedef int (*iv_msghandler)(int, void *, int);
typedef int (*iv_requestlistener)(int, void *, int, int);
typedef int (*iv_hashenumproc)(char *, void *, void *);
typedef int (*iv_hashcmpproc)(char *, void *, char *, void *);
typedef void (*iv_panelupdateshandler)(int, int, int, int);
typedef void (*iv_custombubbledraw)(struct icustombubble_s *);
typedef void (*iv_customherodraw)(struct icustomhero_s *);
struct BookSyncStatus_s {
  enum MencaFileStatus_e menca_status_;
};
struct iprofile_s {
  char *name;
  char *path;
  int type;
  struct ibitmap_s *avatar;
};
struct iprofiles_s {
  struct iprofile_s *profile;
  int count;
};
struct FontForSort_s {
  char *name;
  int flags;
  char *font;
};
struct obex_service_s {
  enum obex_status_e status;
  int auth;
  long int filesize;
  long int transferred;
  char name[128];
  char path[256];
  char description[128];
  char mimetype[64];
};
struct bt_service_obj_s {
  int id;
  enum bt_service_e service;
  enum bt_service_state_e state;
  int lock;
  int users[16];
  union {
    struct obex_service_s obex;
    char service_data[1024];
  };
};
struct iuser_font_s {
  char *show_font_name;
  char *real_font_name;
  struct ifont_s *font;
};
struct ifont_list_s {
  struct iuser_font_s *list;
  int count;
};
struct ifont_menu_s {
  char *menu_title;
  char *current_font;
  FONT_MENU_FLAGS flags;
  iv_fontselecthandler hproc;
  struct ifont_list_s *user_fonts;
};
struct irect_s {
  int x;
  int y;
  int w;
  int h;
  int flags;
};
struct ibitmap_s {
  unsigned short width;
  unsigned short height;
  unsigned short depth;
  unsigned short scanline;
  unsigned char data[0];
};
struct control_panel_s {
  int flags;
};
struct TransparentDefinition {
  char m_TRANSPARENT_MATRIX[256];
  int m_isInitTransparentMatrix;
  int m_PercentOfTransparent;
};
struct ihash_item_s {
  char *name;
  void *value;
  struct ihash_item_s *next;
};
struct ihash_s {
  int prime;
  int count;
  void *(*addproc)(void *);
  iv_hashdelproc delproc;
  struct ihash_item_s **items;
};
struct ifont_s {
  char *name;
  char *family;
  int size;
  unsigned char aa;
  unsigned char isbold;
  unsigned char isitalic;
  unsigned char _r1;
  unsigned short charset;
  unsigned short _r2;
  int color;
  int height;
  int linespacing;
  int baseline;
  void *fdata;
};
struct imenu_s {
  short int type;
  short int index;
  char *text;
  struct imenu_s *submenu;
};
struct imenuex_s {
  short int type;
  short int index;
  char *text;
  struct imenuex_s *submenu;
  struct ibitmap_s *icon;
  void *reserved;
  const struct ifont_s *font;
};
struct icanvas_s {
  int width;
  int height;
  int scanline;
  int depth;
  int clipx1;
  int clipx2;
  int clipy1;
  int clipy2;
  unsigned char *addr;
};
struct icontext_menu_properties_s {
  struct ifont_s *font_normal;
  struct ifont_s *font_selected;
  struct ifont_s *font_disabled;
  int background_color_normal;
  int background_color_disabled;
  int blackout;
  int item_height;
  int item_border_indent_horizontal;
  int separator_indent_horizontal;
  int separator_indent_vertical;
  int separator_height;
  int separator_style;
  int separator_color;
  int separator_frequency;
  int marker_height;
  int marker_indent_horizontal;
  int marker_style;
  int marker_color;
  int border_size;
  int border_radius;
  int title_height;
  int enable_pointer;
  int font_normal_color;
  int font_selected_color;
  int font_disabled_color;
  int bullet_show;
  int bullet_style;
  int item_border_indent_vertical;
  int background_style;
};
struct ifont_selector_properties {
  unsigned short custom_font_enable;
};
struct icontext_menu_s {
  const char *id;
  iv_menuhandler hproc;
  const struct imenuex_s *menuex;
  const struct imenu_s *menu;
  struct irect_s pos_selected_item;
  struct irect_s pos_menu;
  struct icontext_menu_properties_s *properties;
  int active_element;
  short int enable_pointer;
  short int enable_aura;
  short int use_own_font;
  short int update_after_close;
  short int only_choise;
};
struct iapp_caption_s {
  struct irect_s rect_portrait;
  struct irect_s rect_landscape;
  struct ifont_s *font;
  int title_height;
  int background_color;
  short int is_active;
  short int is_uppercase;
};
struct itaskmgr_s {
  int title_height;
  struct ifont_s *title_font;
  struct ifont_s *task_font;
  struct ifont_s *task_title_font;
  int style;
  int profile_present;
  int profile_height;
  struct ifont_s *profile_font;
  int shortcut_height;
  int shortcut_width;
  struct ifont_s *shortcut_font;
  int task_height;
  int full_height;
  int full_width;
  int width;
  int height;
  int x;
  int y;
  int border_size;
  int indent_from_border;
  struct ibitmap_s **bitmap;
  int bitmap_count;
  int separator_size;
  int exit_button_indent;
  int background_style;
  int separator_color;
  int border_color;
};
struct ipager_s {
  struct ifont_s *page_font;
  int height;
  int indent_horizontal;
  int left_width;
  int page_width;
  int rigth_width;
  int separator_size;
  const struct ibitmap_s *icon_left;
  const struct ibitmap_s *icon_right;
  int current_page;
  int total_pages;
  struct irect_s position;
  int orientation;
};
struct iselection_s {
  int selection_style;
  int background_color;
  int background_style;
  int border_size;
  int border_radius;
  int indent_horizontal;
  int indent_left;
  int indent_right;
};
struct iappstyle_s {
  AppStyles app_style;
};
struct ievent_s {
  iv_handler hproc;
  unsigned short type;
  unsigned short mod;
  unsigned short par1;
  unsigned short par2;
};
struct iconfig_s {
  char *filename;
  struct ihash_s *hash;
  struct ihash_s *vhash;
  struct ihash_s *modified_hash;
  char **deleted_keys;
  int changed;
};
struct iconfigedit_s {
  int type;
  const struct ibitmap_s *icon;
  char *text;
  char *hint;
  char *name;
  char *deflt;
  char **variants;
  struct iconfigedit_s *submenu;
  struct ibitmap_s **icon_theme;
};
struct oldconfigedit_s {
  char *text;
  char *name;
  int type;
  char *deflt;
  char **variants;
};
struct tocentry_s {
  int level;
  int page;
  long long int position;
  char *text;
};
struct itimer_s {
  iv_timerproc tp;
  int weak;
  long long int extime;
  char name[32];
  void *context;
  long long int lastchecktime;
};
struct bookinfo_s {
  int type;
  char *typedesc;
  char *path;
  char *filename;
  char *title;
  char *author;
  char *series;
  int numinseries;
  char *genre[10];
  struct ibitmap_s *icon;
  int year;
  long int size;
  long int ctime;
  char *isbn;
  char *meta_id;
  char *first_author;
  int drm;
  char *annotation;
  char *lang;
  char *publisher;
  char *identifiers;
};
struct iv_filetype_s {
  char *extension;
  char *description;
  int type;
  char *program;
  struct ibitmap_s *icon;
};
struct iv_template_s {
  int width;
  int height;
  struct ibitmap_s *background;
  struct ibitmap_s *bg_folder;
  struct ibitmap_s *bg_folder_a;
  struct ibitmap_s *bg_file;
  struct ibitmap_s *bg_file_a;
  struct irect_s iconpos;
  struct irect_s mediaiconpos;
  struct irect_s line1pos;
  struct irect_s line2pos;
  struct irect_s line3pos;
  struct ifont_s *line1font;
  struct ifont_s *line2font;
  struct ifont_s *line3font;
};
struct iv_wlist_s {
  char *word;
  short int x1;
  short int y1;
  short int x2;
  short int y2;
};
struct iv_netinfo_s {
  int connected;
  char name[64];
  char device[64];
  char security[64];
  char prefix[64];
  int index;
  int atime;
  int speed;
  int reserved_0e;
  unsigned long bytes_in;
  unsigned long bytes_out;
  unsigned long packets_in;
  unsigned long packets_out;
};
struct iv_sessioninfo_s {
  char *url;
  char *ctype;
  long int response;
  int length;
  int progress;
};
struct iv_fbinfo_s {
  int version;
  unsigned int flags;
  int shmkey;
  int shmsize;
  int refkey;
  int refsize;
  int width;
  int height;
  int vdepth;
  int ndepth;
  int orientation;
  int _deprecated_cwidth;
  int _deprecated_cheight;
  int scanline;
  int fb_offset;
  int fb_size;
  int ev_offset;
  int ev_size;
  int evhead;
  int evtail;
  int einkversion;
  int reserved[15];
  unsigned char data[0];
  int fb_y_offset;
};
struct subtaskinfo_s {
  int id;
  char *name;
  char *book;
  int fgindex;
  int order;
  int rsv_1s;
};
struct taskinfo_s {
  int task;
  int nsubtasks;
  unsigned int flags;
  int fbshmkey;
  int fbshmsize;
  int mainpid;
  char *appname;
  struct ibitmap_s *icon;
  struct subtaskinfo_s *subtasks;
  int rsv_1;
  int rsv_2;
  int rsv_3;
  int rsv_4;
};
struct iv_mtinfo_s {
  int active;
  int x;
  int y;
  int pressure;
  enum input_dev_e devtype;
  int rsv_2;
  long long int timems;
};
struct apinfo_s {
  char ssid[36];
  int mode;
  int channel;
  WIFI_SECURITY security;
  int quality;
  int level;
  int noise;
  unsigned char mac[8];
  long int timestamp;
};
struct wifi_ap_list_s {
  int ap_quantity;
  struct apinfo_s apinfo[];
};
struct network_interface_array_s {
  unsigned int count;
  network_interface net_int[];
};
struct icolor_map_s {
  int *from_color;
  int *to_color;
  int size;
};
struct icustombubble_s {
  int type;
  struct irect_s bubble_pos;
  struct irect_s arrow_pos;
  struct ibitmap_s *arrow_bmp;
  struct ibitmap_s *icon_bmp;
  struct irect_s text_pos;
  struct ifont_s *font;
  char *text;
};
struct icustomhero_s {
  struct irect_s pos;
  char *name;
  struct ibitmap_s *hero_bmp;
  int max_bubbles;
  struct irect_s **bubbles;
};
struct icustomdialog_s {
  int timeout;
  int bubble_count;
  struct icustombubble_s **bubbles;
  struct icustomhero_s *hero;
  iv_customherodraw hero_draw;
  iv_custombubbledraw bubble_draw;
  iv_dialoghandler cb_handler;
  int cancel_enable_;
};
enum { MAX_BT_SERVICE_USER = 16 };
enum { MSG_ACTUALIZEFRONTLIGHT = 284 };
enum { MSG_UPDATE_SERVICE_STATUSES = 285 };
enum { MSG_FACTORY_RESET = 286 };
enum { MSG_SETTIME_FROM_NTP = 287 };
enum { MSG_GET_IS_TIME_MONOTONIC_AFTER_LAST_NTP_SYNC = 288 };
enum { MSG_GET_PARTNER_ID = 289 };
enum { MSG_UPDATE_PARTNER_ID = 290 };
enum { MSG_BAN_SUSPEND = 291 };
enum { MSG_BACKUP = 292 };
enum { MSG_RESTORE = 293 };
enum { MSG_TASK_SEND_REQUEST_NOWAIT = 1303 };
enum { MSG_START_SERVICES = 1536 };
enum { MSG_LAST_OPEN_OPENED = 1537 };
enum { APP_UID = 101 };
enum { APP_GID = 101 };
enum { SECAPP_UID = 102 };
enum { SECAPP_GID = 102 };
enum { SYSTEMDEPTH = 8 };
enum { MAXMSGSIZE = 65520 };
enum { MSG_REQUEST = 2147483647 };
enum { MSG_XREQUEST = 2080374784 };
enum { MSG_OK = 1 };
enum { MSG_ERROR = 0 };
enum { MSG_FORMAT = 257 };
enum { MSG_SETTIME = 258 };
enum { MSG_SETPROFILE = 259 };
enum { MSG_PWENCRYPT = 260 };
enum { MSG_PWDECRYPT = 261 };
enum { MSG_RESTART = 262 };
enum { MSG_REMOUNTFS = 263 };
enum { MSG_WRITELOGO = 264 };
enum { MSG_RESTORELOGO = 265 };
enum { MSG_SUSPEND = 266 };
enum { MSG_IOC_ENCRYPT = 267 };
enum { MSG_IOC_DECRYPT = 268 };
enum { MSG_REG_CHECK = 269 };
enum { MSG_REG_WRITE = 270 };
enum { MSG_GETSERIAL = 271 };
enum { MSG_REBOOT = 272 };
enum { MSG_REBOOT_AND_UPDATE = 273 };
enum { MSG_TIMESTAMP = 274 };
enum { MSG_UPDATESTATUS = 275 };
enum { MSG_DISABLE_GSENSOR = 276 };
enum { MSG_ENABLE_GSENSOR = 277 };
enum { MSG_CONFIG_CHANGED = 278 };
enum { MSG_SET_LED = 279 };
enum { MSG_ENCRYPT_MEM = 280 };
enum { MSG_DECRYPT_MEM = 281 };
enum { MSG_GETDEVICEID = 282 };
enum { MSG_SETFRONTLIGHT = 283 };
enum { MSG_FBINFO = 513 };
enum { MSG_ORIENTATION = 514 };
enum { MSG_UPDPARTIAL = 515 };
enum { MSG_UPDDYNAMIC = 516 };
enum { MSG_UPDFULL = 517 };
enum { MSG_EINKPM = 518 };
enum { MSG_EINKTEMP = 519 };
enum { MSG_TASK_REGISTER = 1281 };
enum { MSG_TASK_NEWSUBTASK = 1282 };
enum { MSG_TASK_SWITCHSUBTASK = 1283 };
enum { MSG_TASK_ENDSUBTASK = 1284 };
enum { MSG_TASK_SETPARAMETERS = 1285 };
enum { MSG_TASK_SETSUBTASKINFO = 1286 };
enum { MSG_TASK_FOREGROUND = 1287 };
enum { MSG_TASK_BACKGROUND = 1288 };
enum { MSG_TASK_CLOSE = 1289 };
enum { MSG_TASK_LIST = 1290 };
enum { MSG_TASK_PREVIOUS = 1291 };
enum { MSG_TASK_INFO = 1292 };
enum { MSG_TASK_SENDEVENT = 1293 };
enum { MSG_TASK_SENDREQUEST = 1294 };
enum { MSG_TASK_ADDREQLISTENER = 1296 };
enum { MSG_TASK_DELREQLISTENER = 1297 };
enum { MSG_TASK_GLOBALREQUEST = 1298 };
enum { MSG_TASK_SENDEVENTSYNC = 1299 };
enum { MSG_TASK_INITIALIZED = 1300 };
enum { MSG_TASK_PREVIOUS_INSTACK = 1301 };
enum { MSG_TASK_COPY_ACTIVE_FB = 1302 };
enum { MSG_DEVICEKEY = 181452289 };
enum { MSG_RESETKEY = 181452290 };
enum { EVT_INIT = 21 };
enum { EVT_EXIT = 22 };
enum { EVT_SHOW = 23 };
enum { EVT_REPAINT = 43 };
enum { EVT_HIDE = 24 };
enum { EVT_KEYDOWN = 25 };
enum { EVT_KEYPRESS = 25 };
enum { EVT_KEYUP = 26 };
enum { EVT_KEYRELEASE = 26 };
enum { EVT_KEYREPEAT = 28 };
enum { EVT_POINTERUP = 29 };
enum { EVT_POINTERDOWN = 30 };
enum { EVT_POINTERMOVE = 31 };
enum { EVT_POINTERLONG = 34 };
enum { EVT_POINTERHOLD = 35 };
enum { EVT_POINTERDRAG = 44 };
enum { EVT_POINTERCANCEL = 45 };
enum { EVT_ORIENTATION = 32 };
enum { EVT_FOCUS = 36 };
enum { EVT_UNFOCUS = 37 };
enum { EVT_ACTIVATE = 38 };
enum { EVT_MTSYNC = 39 };
enum { EVT_TOUCHUP = 40 };
enum { EVT_TOUCHDOWN = 41 };
enum { EVT_TOUCHMOVE = 42 };
enum { EVT_QN_MOVE = 51 };
enum { EVT_QN_RELEASE = 52 };
enum { EVT_QN_BORDER = 53 };
enum { EVT_SNAPSHOT = 71 };
enum { EVT_FSINCOMING = 72 };
enum { EVT_FSCHANGED = 73 };
enum { EVT_MP_STATECHANGED = 81 };
enum { EVT_MP_TRACKCHANGED = 82 };
enum { EVT_PREVPAGE = 91 };
enum { EVT_NEXTPAGE = 92 };
enum { EVT_OPENDIC = 93 };
enum { EVT_CONTROL_PANEL_ABOUT_TO_OPEN = 94 };
enum { EVT_PANEL_BLUETOOTH_A2DP = 118 };
enum { EVT_TAB = 119 };
enum { EVT_PANEL = 120 };
enum { EVT_PANEL_ICON = 121 };
enum { EVT_PANEL_TEXT = 122 };
enum { EVT_PANEL_PROGRESS = 123 };
enum { EVT_PANEL_MPLAYER = 124 };
enum { EVT_PANEL_USBDRIVE = 125 };
enum { EVT_PANEL_NETWORK = 126 };
enum { EVT_PANEL_CLOCK = 127 };
enum { EVT_PANEL_BLUETOOTH = 128 };
enum { EVT_PANEL_TASKLIST = 129 };
enum { EVT_PANEL_OBREEY_SYNC = 130 };
enum { EVT_PANEL_SETREADINGMODE = 131 };
enum { EVT_PANEL_SETREADINGMODE_INVERT = 132 };
enum { EVT_PANEL_FRONT_LIGHT = 133 };
enum { EVT_GLOBALREQUEST = 149 };
enum { EVT_GLOBALACTION = 150 };
enum { EVT_FOREGROUND = 151 };
enum { EVT_BACKGROUND = 152 };
enum { EVT_SUBTASKCLOSE = 153 };
enum { EVT_CONFIGCHANGED = 154 };
enum { EVT_SAVESTATE = 155 };
enum { EVT_OBREEY_CONFIG_CHANGED = 156 };
enum { EVT_SDIN = 161 };
enum { EVT_SDOUT = 162 };
enum { EVT_BT_RXCOMPLETE = 171 };
enum { EVT_BT_TXCOMPLETE = 172 };
enum { EVT_SYNTH_ENDED = 200 };
enum { EVT_DIC_CLOSED = 201 };
enum { EVT_SHOW_KEYBOARD = 202 };
enum { EVT_TEXTCLEAR = 209 };
enum { EVT_EXT_KB = 210 };
enum { EVT_LETTER = 211 };
enum { EVT_CALLBACK = 212 };
enum { EVT_SCANPROGRESS = 213 };
enum { EVT_STOPSCAN = 214 };
enum { EVT_STARTSCAN = 215 };
enum { EVT_SCANSTOPPED = 216 };
enum { EVT_POSTPONE_TIMED_POWEROFF = 217 };
enum { EVT_FRAME_ACTIVATED = 218 };
enum { EVT_FRAME_DEACTIVATED = 219 };
enum { EVT_READ_PROGRESS_CHANGED = 220 };
enum { EVT_DUMP_BITMAPS_DEBUG_INFO = 221 };
enum { EVT_NET_CONNECTED = 256 };
enum { EVT_NET_DISCONNECTED = 257 };
enum { EVT_NET_FOUND_NEW_FW = 260 };
enum { EVT_SYNTH_POSITION = 261 };
enum { KEY_POWER = 1 };
enum { KEY_DELETE = 8 };
enum { KEY_OK = 10 };
enum { KEY_UP = 17 };
enum { KEY_DOWN = 18 };
enum { KEY_LEFT = 19 };
enum { KEY_RIGHT = 20 };
enum { KEY_MINUS = 21 };
enum { KEY_PLUS = 22 };
enum { KEY_MENU = 23 };
enum { KEY_PREV = 24 };
enum { KEY_NEXT = 25 };
enum { KEY_HOME = 26 };
enum { KEY_BACK = 27 };
enum { KEY_PREV2 = 28 };
enum { KEY_NEXT2 = 29 };
enum { KEY_MUSIC = 30 };
enum { KEY_COVEROPEN = 2 };
enum { KEY_COVERCLOSE = 3 };
enum { KEY_ZOOMOUT = 6 };
enum { KEY_ZOOMIN = 7 };
enum { KEY_SHIFT = 14 };
enum { KEY_LANGUAGECHANGE = 15 };
enum { KEY_KEYBOARDCLOSE = 16 };
enum { KEY_0 = 48 };
enum { KEY_1 = 49 };
enum { KEY_2 = 50 };
enum { KEY_3 = 51 };
enum { KEY_4 = 52 };
enum { KEY_5 = 53 };
enum { KEY_6 = 54 };
enum { KEY_7 = 55 };
enum { KEY_8 = 56 };
enum { KEY_9 = 57 };
enum { KEYMAPPING_GLOBAL = 0 };
enum { KEYMAPPING_TXT = 1 };
enum { KEYMAPPING_PDF = 2 };
enum { BLACK = 0 };
enum { DGRAY = 5592405 };
enum { LGRAY = 11184810 };
enum { WHITE = 16777215 };
enum { ITEM_HEADER = 1 };
enum { ITEM_ACTIVE = 2 };
enum { ITEM_INACTIVE = 3 };
enum { ITEM_SUBMENU = 5 };
enum { ITEM_SEPARATOR = 6 };
enum { ITEM_BULLET = 7 };
enum { ITEM_TYPEMASK = 31 };
enum { ITEM_HIDDEN = 128 };
enum { ITEM_OLDMENU = 32768 };
enum { ITEM_ALTSTYLE = 64 };
enum { KBD_NORMAL = 0 };
enum { KBD_ENTEXT = 1 };
enum { KBD_PHONE = 2 };
enum { KBD_NUMERIC = 4 };
enum { KBD_IPADDR = 5 };
enum { KBD_FILENAME = 6 };
enum { KBD_URL = 7 };
enum { KBD_DATE = 8 };
enum { KBD_TIME = 9 };
enum { KBD_DATETIME = 10 };
enum { KBD_HEX = 11 };
enum { KBD_HOURS = 12 };
enum { KBD_UPPER = 16 };
enum { KBD_LOWER = 32 };
enum { KBD_FIRSTUPPER = 48 };
enum { KBD_PASSWORD = 256 };
enum { KBD_NOSELECT = 512 };
enum { KBD_SCREENTOP = 1024 };
enum { KBD_NOHEADER = 2048 };
enum { KBD_NOEVTSHOW = 4096 };
enum { KBD_SENDKEYBOARDSTATEEVENTS = 8192 };
enum { KBD_NOTOUCH = 16384 };
enum { KBD_PASSEVENTS = 32768 };
enum { KBD_NOUPDATE_AFTER_CLOSE = 65536 };
enum { KBD_EN_DEFAULT = 131072 };
enum { KBD_NOUPDATE_AFTER_OPEN = 262144 };
enum { KBD_NO_SELFCLOSE_ON_OK = 524288 };
enum { KBD_CUSTOM_ENTER_KEY = 1048576 };
enum { KBD_MARKED_ENTER_KEY = 2097152 };
enum { KBD_PASSWORD_WIFI = 4194304 };
enum { KBD_NEXT = 8388608 };
enum { ICON_INFORMATION = 1 };
enum { ICON_QUESTION = 2 };
enum { ICON_WARNING = 3 };
enum { ICON_ERROR = 4 };
enum { ICON_WIFI = 5 };
enum { DEF_BUTTON1 = 0 };
enum { DEF_BUTTON2 = 4096 };
enum { DEF_BUTTON3 = 8192 };
enum { NO_DISMISS = 32768 };
enum { WITH_SIZE = 1 };
enum { LIST_BEGINPAINT = 1 };
enum { LIST_PAINT = 2 };
enum { LIST_ENDPAINT = 3 };
enum { LIST_OPEN = 4 };
enum { LIST_MENU = 5 };
enum { LIST_DELETE = 6 };
enum { LIST_EXIT = 7 };
enum { LIST_ORIENTATION = 8 };
enum { LIST_POINTER = 9 };
enum { LIST_INFO = 11 };
enum { LIST_SCROLL = 12 };
enum { LISTFLAG_SCROLL = 1073741824 };
enum { BMK_CLOSED = -1 };
enum { BMK_SELECTED = 1 };
enum { BMK_ADDED = 2 };
enum { BMK_REMOVED = 3 };
enum { BMK_PAINT = 4 };
enum { CFG_TEXT = 1 };
enum { CFG_CHOICE = 2 };
enum { CFG_INDEX = 3 };
enum { CFG_TIME = 4 };
enum { CFG_FONT = 5 };
enum { CFG_FONTFACE = 6 };
enum { CFG_INFO = 7 };
enum { CFG_NUMBER = 8 };
enum { CFG_ENTEXT = 9 };
enum { CFG_PASSWORD = 10 };
enum { CFG_IPADDR = 11 };
enum { CFG_URL = 12 };
enum { CFG_PHONE = 13 };
enum { CFG_ACTIONS = 14 };
enum { CFG_CHOICE_SPECIAL_FONT = 15 };
enum { CFG_DIRECTORY = 16 };
enum { CFG_HOURS = 17 };
enum { CFG_CHECKBOX = 18 };
enum { CFG_SUBMENU_ACTION = 29 };
enum { CFG_CUSTOM = 30 };
enum { CFG_SUBMENU = 31 };
enum { CFG_MASK = 127 };
enum { CFG_HIDDEN = 128 };
enum { CFG_READONLY = 256 };
enum { CFG_BSCSPEC = 512 };
enum { ALLTASKS = -1 };
enum { MAINTASK = -2 };
enum { OTHERTASKS = -3 };
enum { THISTASK = -4 };
enum { ACTIVETASK = -5 };
enum { MPLAYERTASK = -6 };
enum { DICTIONARYTASK = -7 };
enum { ALLSUBTASKS = -1 };
enum { CURRENTSUBTASK = -6 };
enum { TASK_HIDDEN = 1 };
enum { TASK_COPYLASTFB = 2 };
enum { TASK_NOUPDATEONFOCUS = 4 };
enum { TASK_SINGLEINSTANCE = 8 };
enum { TASK_SPYEVENTS = 16 };
enum { TASK_OUTOFSTACK = 32 };
enum { TASK_NOFORCEDKILL = 64 };
enum { TASK_MAKEACTIVE = 128 };
enum { TASK_GROUP1 = 256 };
enum { TASK_GROUP2 = 512 };
enum { TASK_OOMPROOF = 16384 };
enum { TASK_AUTORESTART = 32768 };
enum { TASK_DONTSENDTASKMSG = 65536 };
enum { TASK_DONTCHANGE = 4294967295 };
enum { RQL_ADD = 1 };
enum { RQL_REPLACE = 2 };
enum { RQL_ADDIFNONE = 3 };
enum { RQL_REMOVE = 4 };
enum { REQ_KEYLOCK = 65 };
enum { REQ_MAINMENU = 66 };
enum { REQ_EXIT = 67 };
enum { REQ_LASTOPEN = 68 };
enum { REQ_PROFILES = 69 };
enum { REQ_SCREENSHOT = 70 };
enum { REQ_CALC = 71 };
enum { REQ_PLAYER = 72 };
enum { REQ_PLAYPAUSE = 73 };
enum { REQ_VOLUMEUP = 74 };
enum { REQ_VOLUMEDOWN = 75 };
enum { REQ_NETWORK = 76 };
enum { REQ_BTSWITCH = 77 };
enum { REQ_DROPCONN = 78 };
enum { REQ_TASKMGR = 79 };
enum { REQ_SWITCHTASK = 80 };
enum { REQ_FLIPTASK = 81 };
enum { REQ_KILLTASK = 82 };
enum { REQ_POWEROFF = 83 };
enum { REQ_OPENBOOK = 84 };
enum { REQ_BOOKSTATE = 85 };
enum { REQ_BOOKOPENED = 86 };
enum { REQ_HEADCHNG = 87 };
enum { REQ_OPENBOOK2 = 88 };
enum { REQ_FRONTLIGHT = 89 };
enum { REQ_KEYUNLOCK = 90 };
enum { REQ_HOURGLASS = 91 };
enum { REQ_MESSAGEBOX = 92 };
enum { REQ_KEYHARDLOCK = 93 };
enum { REQ_PB_CLOUD_NEW_POSITION = 94 };
enum { ALIGN_LEFT = 1 };
enum { ALIGN_CENTER = 2 };
enum { ALIGN_RIGHT = 4 };
enum { ALIGN_FIT = 8 };
enum { VALIGN_TOP = 16 };
enum { VALIGN_MIDDLE = 32 };
enum { VALIGN_BOTTOM = 64 };
enum { ROTATE = 128 };
enum { HYPHENS = 256 };
enum { DOTS = 512 };
enum { RTLAUTO = 1024 };
enum { UNDERLINE = 2048 };
enum { STRETCH = 4096 };
enum { TILE = 8192 };
enum { TO_UPPER = 16384 };
enum { FR_CLOSE = 1 };
enum { FR_MOVEUP = 2 };
enum { FR_MOVEDOWN = 4 };
enum { FR_DICTIONARY = 67108864 };
enum { FR_NOMARGIN = 134217728 };
enum { FR_OVERLAP = 268435456 };
enum { FR_HEADER = 536870912 };
enum { FR_UPDATE = 1073741824 };
enum { FR_INFO = 65536 };
enum { FR_WARNING = 131072 };
enum { FR_ERROR = 196608 };
enum { FR_DIALOG = 262144 };
enum { FR_APP = 327680 };
enum { ARROW_LEFT = 1 };
enum { ARROW_RIGHT = 2 };
enum { ARROW_UP = 3 };
enum { ARROW_DOWN = 4 };
enum { SYMBOL_OK = 5 };
enum { SYMBOL_PAUSE = 6 };
enum { SYMBOL_BULLET = 7 };
enum { ARROW_UPDOWN = 8 };
enum { SYMBOL_MENU = 9 };
enum { IMAGE_BW = 1 };
enum { IMAGE_GRAY2 = 2 };
enum { IMAGE_GRAY4 = 4 };
enum { IMAGE_GRAY8 = 8 };
enum { IMAGE_RGB = 24 };
enum { ROTATE0 = 0 };
enum { ROTATE90 = 1 };
enum { ROTATE270 = 2 };
enum { ROTATE180 = 3 };
enum { XMIRROR = 4 };
enum { YMIRROR = 8 };
enum { A2DITHER = 16 };
enum { DITHER_THRESHOLD = 0 };
enum { DITHER_PATTERN = 1 };
enum { DITHER_DIFFUSION = 2 };
enum { QN_X = 4096 };
enum { QN_Y = 8192 };
enum { QN_XY = 12288 };
enum { QN_SWAIT = 16384 };
enum { QN_RWAIT = 32768 };
enum { QN_CLEANUP = 65536 };
enum { MP_ONCE = 0 };
enum { MP_CONTINUOUS = 1 };
enum { MP_RANDOM = 2 };
enum { FTYPE_UNKNOWN = 0 };
enum { FTYPE_BOOK = 1 };
enum { FTYPE_PICTURE = 2 };
enum { FTYPE_MUSIC = 3 };
enum { FTYPE_APPLICATION = 4 };
enum { FTYPE_WEBLINK = 5 };
enum { FTYPE_FOLDER = 255 };
enum { OB_ADDTOLAST = 1 };
enum { OB_WITHRETURN = 2 };
enum { OB_PARAMSFIRST = 4 };
enum { OB_NONEWTASK = 8 };
enum { OB_SOFTUPDATE = 16 };
enum { OB_NOHOURGLASS = 32 };
enum { NET_BLUETOOTH = 1 };
enum { NET_WIFI = 2 };
enum { NET_CDMA3G = 4 };
enum { NET_BTREADY = 256 };
enum { NET_WIFIREADY = 512 };
enum { NET_CDMA3GREADY = 1024 };
enum { NET_CONNECTED = 3840 };
enum { CONN_GPRS = 1 };
enum { CONN_WIFI = 2 };
enum { CONN_CDMA3G = 3 };
enum { BLUETOOTH_OFF = 0 };
enum { BLUETOOTH_HIDDEN = 1 };
enum { BLUETOOTH_VISIBLE = 2 };
enum { NET_OK = 0 };
enum { NET_CONNECT = 1 };
enum { NET_TRANSFER = 2 };
enum { NET_FAIL = -11 };
enum { NET_ABORTED = -12 };
enum { NET_EINIT = -13 };
enum { NET_EWRONGID = -14 };
enum { NET_ENETWORK = -15 };
enum { NET_EFILE = -16 };
enum { NET_EPIPE = -17 };
enum { NET_ETHREAD = -18 };
enum { NET_EPROTO = -19 };
enum { NET_EURL = -20 };
enum { NET_ERESOLVE = -21 };
enum { NET_ECONNECT = -22 };
enum { NET_EACCESS = -23 };
enum { NET_ENOTFOUND = -24 };
enum { NET_EPARTIAL = -25 };
enum { NET_EBROKEN = -26 };
enum { NET_ETIMEOUT = -27 };
enum { NET_ESERVER = -28 };
enum { NET_EHTTP = -29 };
enum { NET_EHARDWARE = -30 };
enum { NET_ENOTCONF = -31 };
enum { NET_EBADCONF = -32 };
enum { NET_ENODEVICE = -33 };
enum { NET_EPPP = -34 };
enum { NET_EDISABLED = -35 };
enum { NET_EDHCP = -36 };
enum { NET_EWRONGKEY = -37 };
enum { NET_EAUTH = -38 };
enum { GSENSOR_OFF = 0 };
enum { GSENSOR_ON = 1 };
enum { GSENSOR_INTR = 2 };
enum { VN_NOPATH = 1 };
enum { VN_NOESCAPE = 2 };
enum { VN_ABSOLUTE = 4 };
enum { VN_RELATIVE = 8 };
enum { A2DP_DISCONNECTED = 0 };
enum { A2DP_CONNECTED_TO_SNK = 1 };
enum { CF_CONFIG_RESUME = 1 };
enum { FONT_ACTIVATE_CODE = 2410017735 };
enum { IV_OSY_STATUS_TURNED_OFF = 0 };
enum { IV_OSY_STATUS_WRONG_LOGIN_PASSWORD = 1 };
enum { IV_OSY_STATUS_DOWNLOADING = 2 };
enum { IV_OSY_STATUS_PAUSED = 3 };
enum { IV_OSY_STATUS_IDLE = 4 };
enum { IV_OSY_STATUS_ERROR = 5 };
void InitInkview(int);
void CalibrateGSensor();
void CloseApp();
int GetGlobalOrientation();
int GetOrientation();
void InkViewMain(iv_handler);
struct irect_s iRect(int, int, int, int, int);
void OpenScreen();
void OpenScreenExt();
int QueryGSensor();
int ReadGSensor(int *, int *, int *);
int ScreenHeight();
int ScreenWidth();
void SetGlobalOrientation(int);
void SetGSensor(int);
void SetGSensorEnabled(bool onOff);
bool IsGSensorEnabled();
int GetGSensorOrientation();
void SetOrientation(int);
void AbortTransfer(int);
void AddLastOpen(const char *);
void AddScrolledArea(struct irect_s *, int);
void AddTranslation(const char *, const char *);
int AdjustDirectionKeys(int);
void adjustAreaDefault(unsigned char* data, int scanline, int width, int height);
void adjustAreaWithVibrance(unsigned char* data, int scanline, int width, int height, float vibrance);
void adjustAreaWithLabColorsSaturation(unsigned char* data, int scanline, int width, int height, double koef);
void adjustAreaWithSaturationBrightnessAndDithering(unsigned char* data, int scanline, int width, int height, int * saturation_table, int * value_table, bool dithering);
char *arc_filename(const char *);
int base64_decode(const char *, unsigned char *, int);
int base64_encode(const unsigned char *, int, char *);
struct ibitmap_s *BitmapFromScreen(int, int, int, int);
struct ibitmap_s *BitmapFromScreenR(int, int, int, int, int);
struct ibitmap_s *BitmapStretchCopy(const struct ibitmap_s *, int, int, int, int, int, int);
void BookPreparing(const char *);
void BookReady(const char *);
int BtSendFiles(char *, char **);
void CalibrateTouchDevice(enum input_dev_e);
void CalibrateTouchpanel();
int CharWidth(unsigned short);
char *CheckAssociatedFile(const char *, int);
int CheckFramePointer(int, int, int, int, int, int, int);
void clean_proxy_object(proxy_settings **);
void ClearAllScrolledAreas();
void ClearScreen();
void ClearTimer(iv_timerproc);
void ClearTimerByName(const char *);
void ClearTimerEx(iv_timerprocEx, void *);
void CloseAllTasks();
void CloseConfig(struct iconfig_s *);
void CloseConfigLevel();
void CloseConfigNoSave(struct iconfig_s *);
void CloseContextMenu(struct icontext_menu_s *);
void CloseDialog();
void CloseDictionary();
void CloseFont(struct ifont_s *);
void CloseKeyboard();
void ClosePlayer();
void CloseProgressbar();
void CloseSession(int);
int CloseTask(int, int, int);
struct icolor_map_s *ColorMapCreate(int);
void ColorMapDestroy(struct icolor_map_s **);
int convert_to_utf(const char *, char *, int, const char *);
void CopyActiveFb(void);
struct ibitmap_s *CopyBitmap(const struct ibitmap_s *);
struct ibitmap_s *CopyBitmapDepth4To8(const struct ibitmap_s *);
int copy_file(const char *, const char *);
int copy_file_with_af(const char *, const char *);
proxy_settings *copy_proxy_object(proxy_settings *);
struct ibitmap_s *CoverCacheGet(enum COVERCACHE_STORAGES_e, const char *);
int CoverCachePut(enum COVERCACHE_STORAGES_e, const char *, struct ibitmap_s *);
int FastBookHash(const char *, char *, int);
unsigned int crc32hash(const char *, unsigned int);
struct icontext_menu_s *CreateContextMenu(const char *);
void CreateEmptyNote(const char *);
void CreateNote(const char *, const char *, long long int);
void CreateNoteFromImages(const char *, const char *, long long int, struct ibitmap_s *, struct ibitmap_s *);
void CreateNoteFromPage(const char *, const char *, long long int);
int CreateProfile(const char *, int);
proxy_settings *create_proxy_object(enum proxy_type_e, const char *, int, const char *, const char *);
char *CurrentDateStr();
struct icustomdialog_s *CustomDialogCreate(eBubbleTypes, const char *, int);
void CustomDialogDestroy(struct icustomdialog_s *);
void CustomDialogRender(struct icustomdialog_s *);
void CustomDialogShow(struct icustomdialog_s *);
char *DateStr(long int);
void DeleteInt(struct iconfig_s *, const char *);
int DeleteProfile(const char *);
void delete_proxy(void);
void DeleteString(struct iconfig_s *, const char *);
void Dialog(int, const char *, const char *, const char *, const char *, iv_dialoghandler);
void Dialog3(int, const char *, const char *, const char *, const char *, const char *, iv_dialoghandler);
int DialogSynchro(int, const char *, const char *, const char *, const char *, const char *);
void DimArea(int, int, int, int, int);
void DisableExitHourglass();
void DitherArea(int, int, int, int, int, int);
void DitherAreaQuick2Level(int, int, int, int);
int DownloadTo(int, const char *, const char *, const char *, int);
int DownloadTo_Crutch(int, const char *, const char *, const char *, int);
void DrawApplicationCaption(const char *, const struct irect_s *);
void DrawBitmap(int, int, const struct ibitmap_s *);
void DrawBitmapArea(int, int, const struct ibitmap_s *, int, int, int, int);
void DrawBitmapRect(int, int, int, int, const struct ibitmap_s *, int);
void DrawBitmapRect2(const struct irect_s *, const struct ibitmap_s *);
void DrawBorder(const struct irect_s *, int, int, int, int);
void DrawCircle(int, int, int, int);
void DrawDiagonalHatch(int, int, int, int, int, int);
void DrawDiagonalHatchLimits(int, int, int, int, int, int, int (*)(int, int));
void DrawFrame(int, int, int, int, struct ibitmap_s *, char *, int, struct irect_s *);
void DrawLine(int, int, int, int, int);
void DrawLineEx(int, int, int, int, int, int);
void DrawPager(struct ipager_s *);
int DrawPanel(const struct ibitmap_s *, const char *, const char *, int);
int DrawPanel2(const struct ibitmap_s *, const char *, const char *, int, int);
int DrawPanel3(const struct ibitmap_s *, int, int, int);
int DrawPanel4(const struct ibitmap_s *, const char *, int, int, int);
int DrawPanel5(const struct ibitmap_s *, const char *, const char *, int, int);
void DrawPickOut(int, int, int, int, const char *);
void DrawPickOutEx(const struct irect_s *, const char *);
void DrawPixel(int, int, int);
void DrawRect(int, int, int, int, int);
void DrawRectRound(int, int, int, int, int, int);
void DrawSelection(int, int, int, int, int);
void DrawString(int, int, const char *);
void DrawStringR(int, int, const char *);
int DrawSymbol(int, int, int);
int DrawTabs(const struct ibitmap_s *, int, int);
char *DrawTextRect(int, int, int, int, const char *, int);
char *DrawTextRect2(const struct irect_s *, const char *);
char *DrawTextRect3(int, int, int, int, const char *, int, int *);
void DynamicUpdate(int, int, int, int);
void DynamicUpdateA2(int, int, int, int);
void DynamicUpdateBW(int, int, int, int);
char **EnumBTdevices();
char **EnumConnections();
char **EnumDictionaries();
char **EnumFonts();
struct FontForSort_s *EnumFontsEx();
struct FontForSort_s *EnumFontsFromDirectoryEx(const char *, const char *);
void FreeFontsForSort(struct FontForSort_s *);
char **EnumFontsFromDirectory(const char *, const char *);
char **EnumKeyboards();
char **EnumLanguages();
char **EnumNotepads();
struct ibitmap_s **EnumProfileAvatars();
char **EnumProfiles();
char **EnumThemes();
char **EnumWirelessNetworks();
int escape(const char *, char *, int);
void ExitUpdateA2();
struct iv_filetype_s *FileType(const char *);
struct iv_filetype_s *FileTypeExt(const char *, struct stat *);
void FillArea(int, int, int, int, int);
void FillAreaRect(const struct irect_s *, int);
char *FindIsbnInText(const char *);
int FindTaskByAppName(const char *);
int FindTaskByBook(const char *, int *, int *);
void FineUpdate();
int FineUpdateSupported();
void FlushEvents();
void FlushLastOpen();
void ForcingSleep(void);
void FullUpdate();
void FullUpdateHQ();
int GetA2dpStatus();
void GetActiveTask(int *, int *);
AppStyles GetAppGlobalStyle();
AppStyles GetAppStyle(const char *);
struct iappstyle_s *GetAppStyleEx(const char *);
struct BookSyncStatus_s GetBookSyncStatus(const char *);
char *GetAssociatedFile(const char *, int);
int GetBatteryPower();
int GetBluetoothMode();
struct ibitmap_s *GetBookCover(const char *, int, int);
struct bookinfo_s *GetBookInfo(const char *);
struct bookinfo_s *GetBookInfoExt(const char *, const char *);
char *GetBookISBN(const char *);
int GetBTservice(const char *, const char *);
struct icanvas_s *GetCanvas();
int GetCaptionHeight();
void GetClip(int *, int *, int *, int *);
struct irect_s GetClipRect();
const char *GetCurrentLangText(const char *);
char *GetCurrentProfile();
int GetCurrentTask();
int GetCurrentTrack();
const char *GetCustomFontString();
char *GetDefaultUserAgent();
unsigned char *GetDeviceFingerprint();
char *GetDeviceKey();
char *GetDeviceModel();
int GetDialogShow();
unsigned short *get_encoding_table(const char *);
void GetEqualizer(int *);
iv_handler GetEventHandler();
const char *GetExternalCardSerialNumber();
const char *GetFileHandler(const char *);
const struct ifont_s *GetFont();
struct ifont_selector_properties *GetFontSelectorProperties();
struct iconfig_s *GetGlobalConfig();
int GetHardwareDepth();
char *GetHardwareType();
const char *GetHeader(int, const char *);
int GetHighVolumeMaxInterval();
int GetHighVolumeTimeout();
char *GetHw3GIMEI();
char *GetHwAddress();
char *GetHwBTAddress();
int GetKeyboardFlags();
void GetKeyboardRect(struct irect_s *);
struct irect_s GetKeyboardRectWithParams(char *, char *, int);
void GetKeyMapping(const char **, const char **);
void GetKeyMappingEx(int, const char **, const char **, int);
struct ibitmap_s *GetKeyResource(const char *, const struct ibitmap_s *);
const char *GetLangText(const char *);
const char *GetLangTextF(const char *, ...);
const char *GetLangTextPlural(const char *, int);
int GetLastNetConnectionError(void);
int NetMgr(int);
int NetMgrStatus(void);
int NetMgrPing(void);
char **GetLastOpen();
int GetListHeaderLevel();
struct irect_s GetMenuRect(const struct imenu_s *);
struct irect_s GetMenuRectEx(const struct imenuex_s *);
int GetMultilineStringWidth(const char *, const int, struct ifont_s *, const int);
struct network_interface_array_s *GetNetDNS(void);
int GetNetList(const char *);
int NetAdd(const char *);
int NetDelete(const char *);
int NetSelect(const char *);
int NetDelete_by_ssid(const char *);
int NetSelect_by_ssid(const char *);
network_interface *GetNetGateway(const network_interface *);
const char *get_partner_id(void);
int get_keylock();
int is_enough_free_space();
int get_screen_dpi();
int isHighPriorityJobRunning();
void startHighPriorityJob(int, int);
void finishHighPriorityJob(int);
int haveDictionaryKeyboard();
network_interface_info *GetNetInfo(const network_interface *);
int GetNetSignalQuality(void);
NET_STATE GetNetState(void);
int GetPagerHeight(struct ipager_s *);
struct irect_s GetPagerRect(struct ipager_s *);
int GetPanelType();
int GetPlayerMode();
int GetPlayerState();
char **GetPlaylist();
void GetPreviousTask(int *, int *);
void GetPreviousTaskInStack(int *, int *);
struct ibitmap_s *GetProfileAvatar(const char *);
int GetProfileType(const char *);
proxy_settings *get_proxy(void);
char *GetProxyUrl();
struct ibitmap_s *GetResource(const char *, const struct ibitmap_s *);
int GetSafeVolumeLimit();
char *GetSerialNumber();
struct iv_sessioninfo_s *GetSessionInfo(int);
int GetSessionStatus(int);
int GetSleepmode();
char *GetSoftwareVersion();
struct iv_filetype_s *GetSupportedFileTypes();
int GetSupportedFileTypesLength();
struct icanvas_s *GetTaskFramebuffer(int);
struct iv_fbinfo_s *GetTaskFramebufferInfo(int);
struct taskinfo_s *GetTaskInfo(int);
int GetTaskList(int *, int);
int GetTemperature();
struct ifont_s *GetThemeFont(const char *, const char *);
int GetThemeInt(const char *, int);
void GetThemeRect(const char *, struct irect_s *, int, int, int, int, int);
const char *GetThemeString(const char *, const char *);
struct iv_mtinfo_s *GetTouchInfo();
struct iv_mtinfo_s *GetTouchInfoI(unsigned int);
int GetTrackPosition();
int GetTrackSize();
char *GetUserAgent();
int GetVolume();
char *GetWaveformFilename();
struct wifi_ap_list_s *GetWiFiScanResults(struct wifi_ap_list_s *);
int GoSleep(int, int);
void GoToBackground();
void hash_add(struct ihash_s *, const char *, const char *);
void hash_clear(struct ihash_s *);
struct ihash_s *hash_copy(struct ihash_s *);
int hash_copy_to(struct ihash_s *, struct ihash_s *);
int hash_count(struct ihash_s *);
void hash_delete(struct ihash_s *, const char *);
void hash_destroy(struct ihash_s *);
void hash_enumerate(struct ihash_s *, iv_hashcmpproc, iv_hashenumproc, void *);
const char *hash_find(struct ihash_s *, const char *);
struct ihash_s *hash_merge(struct ihash_s *, struct ihash_s *);
int hash_merge_to(struct ihash_s *, struct ihash_s *, struct ihash_s *);
struct ihash_s *hash_new(int);
int HavePowerForSoftwareUpdate();
void HideHourglass();
int HQUpdateSupported();
int hw_get_lux_raw(void);
int hw_is_frontlight_auto(void);
int hw_is_frontlight_auto_supported(void);
void hw_set_frontlight_auto_enabled(int);
int GetFrontlightVersion(void);
int GetFrontlightState(void);
void SetFrontlightState(int);
int GetFrontlightEnabled();
void SetFrontlightEnabled(int);
void SetFrontlightStateEx(int, int);
void OpenFrontLightConfig();
void SwitchFrontlightState();
int GetFrontlightColor(void);
void SetFrontlightColor(int);
void IncreaseHighVolumeInterval(int);
void InvertArea(int, int, int, int);
void InvertAreaBW(int, int, int, int);
void InvertAreaMap(int, int, int, int, struct icolor_map_s *);
char IsAnyEvents();
int IsAnyScrolledArea();
int IsBookRTL();
int IsCharging();
int IsInA2Update();
int IsInRect(int, int, const struct irect_s *);
int IsJoystickButtonsPresent();
int IsKeyboardOpened();
int IsKeyPressed(int);
int IsPagerEvent(struct ipager_s *, int, int, int);
int IsPlayingMP3();
unsigned short IsResourcePresent(const char *);
int IsRTL();
int IsSDinserted();
int IsShowPanelReader();
int IsTaskActive();
int IsUSBconnected();
int iv_access(const char *, int);
void iv_buildpath(const char *);
int iv_closedir(struct __dirstream *);
char *iv_evttype(int);
void iv_fullscreen();
int iv_get_obreey_status();
long int iv_ipc_cmd(long int, long int);
long int iv_ipc_request_with_timeout(long int, long int, unsigned char *, int, int, int);
long int iv_ipc_request(long int, long int, unsigned char *, int, int);
long int iv_ipc_request_secure(long int, long int, unsigned char *, int, int);
int iv_mkdir(const char *, unsigned int);
void iv_nofullscreen();
struct __dirstream *iv_opendir(const char *);
void iv_preload(const char *, int);
struct dirent *iv_readdir(struct __dirstream *);
void iv_reflow_addchar(int, int, int, int, int);
void iv_reflow_addimage(int, int, int, int, int);
void iv_reflow_bt();
void iv_reflow_clear();
void iv_reflow_div();
void iv_reflow_et();
int iv_reflow_getchar(int *, int *);
int iv_reflow_getimage(int *, int *, int *);
char *iv_reflow_getword(int, int *, int *, int *, int *, int *);
void iv_reflow_render(int);
void iv_reflow_start(int, int, int, int, int);
int iv_reflow_subpages();
int iv_reflow_words();
int iv_rename(const char *, const char *);
int iv_rmdir(const char *);
void iv_setbgresponse(int);
void iv_sleepmode(int);
int iv_stat(const char *, struct stat *);
int iv_strcasecmp(const char *, const char *);
int iv_strcmp(const char *, const char *);
int iv_strncasecmp(const char *, const char *, size_t);
int iv_strncmp(const char *, const char *, size_t);
void iv_sync();
int iv_truncate(const char *, int);
int iv_unlink(const char *);
int iv_validate_name(const char *, int);
void iv_wait_task_activation(int);
void LeaveInkViewMain();
struct iapp_caption_s *LoadApplicationCaptionProperties();
struct ibitmap_s *LoadBitmap(const char *);
struct icontext_menu_properties_s *LoadContextMenuProperties();
void LoadHighVolumeTimeout();
struct ibitmap_s *LoadJPEG(const char *, int, int, int, int, int);
void LoadKeyboard(const char *);
void LoadLanguage(const char *);
struct ipager_s *LoadPagerProperties();
void LoadPlaylist(char **);
struct ibitmap_s *LoadPNG(const char *, int);
struct ibitmap_s *LoadPNGStretch(const char *, int, int, int, int);
struct iselection_s *LoadSelectionProperties(const char *);
struct itaskmgr_s *LoadTaskManagerProperties();
struct ibitmap_s *LoadTIFF(const char *, int, int, int, int, int);
void LockDevice();
int LookupNext(char **, char **);
int LookupPrevious(char **, char **);
int LookupWord(const char *, char **, char **);
int LookupWordExact(const char *, char **, char **);
void MD5PartFile(const char *, unsigned char *);
void md5sum(const unsigned char *, int, unsigned char *);
struct irect_s MergeClipRect(const struct irect_s *);
void Message(int, const char *, const char *, int);
int MinimalTextRectWidth(int, const char *);
void MirrorBitmap(struct ibitmap_s *, int);
void MoveBitmap(struct ibitmap_s *, int);
void MoveBitmapRight(struct ibitmap_s *, int);
int move_file(const char *, const char *);
int move_file_with_af(const char *, const char *);
int MultitaskingSupported();
int NetConnect(const char *);
int NetConnect2(const char *, int);
int NetConnectAsync(int (*)(int));
int NetConnectSilent(const char *);
int NetDisconnect();
const char *NetError(int);
void NetErrorMessage(int);
struct iv_netinfo_s *NetInfo();
struct ibitmap_s *NewBitmap(int, int);
int NewSession();
int NewSubtask(char *);
int NewTask(const char *, char *const *, const char *, const char *, const struct ibitmap_s *, unsigned int);
int NewTaskEx(const char *, char *const *, const char *, const char *, const struct ibitmap_s *, unsigned int, int);
void NextTrack();
void NotifyConfigChanged();
void ClearConfig(struct iconfig_s *);
int OpenBook(const char *, const char *, int);
int OpenBook2(const char *, int, const char *const *, int);
void OpenBookmarks(int, long long int, int *, long long int *, int *, int, iv_bmkhandler);
void OpenBTdevicesMenu(char *, int, int, iv_itemchangehandler);
void OpenCalendar();
struct iconfig_s *OpenConfig(const char *, struct iconfigedit_s *);
void OpenConfigEditor(const char *, struct iconfig_s *, struct iconfigedit_s *, iv_confighandler, iv_itemchangehandler);
void OpenConfigSubmenu(const char *, struct iconfigedit_s *);
void OpenConfigSubmenuExt(const char *, struct iconfigedit_s *, int);
void OpenContents(struct tocentry_s *, int, long long int, iv_tochandler);
void OpenContextMenu(const struct icontext_menu_s *);
void OpenControlledDictionaryView(pointer_to_word_hand_t, struct iv_wlist_s *, const char *);
void OpenControlPanel(struct control_panel_s *);
void OpenCustomKeyboard(const char *, const char *, char *, int, int, iv_keyboardhandler);
int GetWordListWithPrefix(const char *, int, char ***);
int OpenDictionary(const char *);
void OpenDictionaryView(struct iv_wlist_s *, const char *);
void OpenDirectorySelector(const char *, char *, int, iv_dirselecthandler);
void OpenDummyList(const char *, const struct ibitmap_s *, char *, iv_listhandler);
void OpenFastTranslation(pointer_to_word_hand_t, struct iv_wlist_s *, int, const char *);
struct ifont_s *OpenFont(const char *, int, int);
void OpenFontSelector(const char *, const char *, int, iv_fontselecthandler);
void OpenFontSelectorEx(const struct ifont_menu_s *);
struct ifont_menu_s GetFontMenuStruct();
void SetFontMenuStruct(struct ifont_menu_s *);
void ClearFontMenuStruct(struct ifont_menu_s *);
void ClearFontListStruct(struct ifont_list_s *);
void OpenKeyboard(const char *, char *, int, int, iv_keyboardhandler);
void OpenKeyboardEx(const char *, char *, int, int, void (*)(char *, void *), void *);
void OpenLastBooks();
void OpenList(const char *, const struct ibitmap_s *, int, int, int, int, iv_listhandler);
void OpenMainMenu();
void OpenMenu(struct imenu_s *, int, int, int, iv_menuhandler);
void OpenMenu3x3(const struct ibitmap_s *, const char **, iv_menuhandler);
void OpenMenuEx(struct imenuex_s *, int, int, int, iv_menuhandler);
void OpenNetworkInfo();
void OpenNotepad(const char *);
void OpenNotesMenu(const char *, const char *, long long int);
void OpenPageSelector(iv_pageselecthandler);
void OpenPlayer();
void OpenProfileSelector();
void OpenProgressbar(int, const char *, const char *, int, iv_dialoghandler);
void OpenRotateBox(iv_rotatehandler);
void OpenTaskList();
void OpenTheme(const char *);
void OpenTimeEdit(const char *, int, int, long int, iv_timeedithandler);
void PackParameters(int, const char *const *, void **, int *);
int PagerHandler(struct ipager_s *, int, int, int);
int PageSnapshot();
int PanelHeight();
void PartialUpdate(int, int, int, int);
void PartialUpdateBlack(int, int, int, int);
void PartialUpdateBW(int, int, int, int);
void PartialUpdateDU4(int, int, int, int);
void PartialUpdateHQ(int, int, int, int);
void Path2String(const char *, char *, int);
void PauseTransfer(int);
void PlayFile(const char *);
void PlayTrack(int);
int PostponeTimedPoweroff(void);
void PowerOff();
void PreviousTrack();
void ProcessEventLoop();
void PrepareForLoop(iv_handler);
void ClearOnExit();
unsigned long QueryDeviceButtons();
int QueryHeadphone();
int QueryNetwork();
long long int QueryTimer(iv_timerproc);
long long int QueryTimerEx(iv_timerprocEx, void *);
int QueryTouchpanel();
void *QuickDownload(const char *, int *, int);
void *QuickDownloadExt(const char *, int *, int, char *, char *);
void *QuickDownloadExt2(const char *, int *, int, char *, char *, int *);
void QuickFloyd16Dither(unsigned char *, int, int, int, int, int);
void QuickNavigator(int, int, int, int, int, int, int);
int QuickNavigatorSupported(int);
int ReadInt(struct iconfig_s *, const char *, int);
const char *ReadSecret(struct iconfig_s *, const char *, const char *);
const char *ReadString(struct iconfig_s *, const char *, const char *);
int recurse_action(const char *, iv_recurser, void *, int, int);
int RefreshConfig(struct iconfig_s **);
void RegisterFontList(struct ifont_s **, int);
void ReleaseTaskFramebuffer(struct icanvas_s *);
void RemoveScrolledArea(struct irect_s *);
int RenameProfile(const char *, const char *);
void Repaint();
void ResetHighVolumeTimeout();
int RestoreStartupLogo();
void ResumeTransfer(int);
int SafeMode();
int SaveBitmap(const char *, const struct ibitmap_s *);
int SaveConfig(struct iconfig_s *);
void SaveHighVolumeTimeout();
int SaveJPEG(const char *, struct ibitmap_s *, int);
int SavePNG(const char *, const struct ibitmap_s *);
void ScheduleUpdate(int, int, int, int, int);
void SendEvent(iv_handler, int, int, int);
int SendEventSyncTo(int, int, int, int);
int SendEventTo(int, int, int, int);
int SendGlobalRequest(int);
int SendMessageTo(int, int, void *, int);
int SendRequest(int, void *, int, int, int);
int SendRequestNoWait(int, void *, int, int);
int SendRequestTo(int, int, void *, int, int, int);
int SendRequestToNoWait(int, int, void *, int, int);
int SetActiveTask(int, int);
void SetApplicationCaptionHeight(int);
void SetAutoPowerOff(int);
int SetBluetoothMode(int, int);
void SetCanvas(struct icanvas_s *);
void SetClip(int, int, int, int);
void SetClipRect(const struct irect_s *);
void SetConfigEditorBackground(struct ibitmap_s *);
void SetContextMenu(const struct icontext_menu_s *);
void SetCurrentApplicationAttribute(APPLICATION_ATTRIBUTE, int);
void SetCurrentProfile(const char *, int);
int GetProfilesCountAfterEnum();
int ScanProfiles(const char *, int, struct iprofiles_s *);
int GetLocalProfilesLimit();
int GetSDProfilesLimit();
int GetProfilesLimit();
void ClearProfilesStruct(struct iprofiles_s *);
void ClearProfileStruct(struct iprofile_s *);
int GetProfilesList(struct iprofiles_s *);
int DeleteProfileEx(const struct iprofile_s *);
int RenameProfileEx(const struct iprofile_s *, const char *);
int GetCurrentProfileEx(struct iprofile_s *);
int SetCurrentProfileEx(const struct iprofile_s *);
int GetProfilesCount();
void SetEqualizer(int *);
iv_handler SetEventHandler(iv_handler);
iv_handler SetEventHandlerEx(iv_handler);
void SetFileHandler(const char *, const char *);
void SetFont(const struct ifont_s *, int);
void SetHardTimer(const char *, iv_timerproc, int);
void SetHardTimerEx(const char *, iv_timerprocEx, void *, int);
void SetKeyboardRate(int, int);
void SetListHeaderLevel(int);
void SetLoadImageFlags(int);
void SetManualPanelUpdates(int, iv_panelupdateshandler);
void SetMenuFont(struct ifont_s *);
void SetMessageHandler(iv_msghandler);
void SetMinimalXScrollIndent(struct irect_s *, int);
void SetMinimalYScrollIndent(struct irect_s *, int);
int SetPanelSeparatorEnabled(int);
int IsPanelSeparatorEnabled();
void InitPanel();
void SetPanelKeyForFullScreenEnabled(const char *);
void SetPanelType(int);
void SetPlayerMode(int);
void SetPlayerState(int);
void SetPort(int);
int SetProfileAvatar(const char *, struct ibitmap_s *);
int set_proxy(proxy_settings *);
void SetProxy(int, const char *, int, const char *, const char *);
void SetQuickNavigatorXY(int, int);
void SetReadingMode(int, int, int);
int SetRequestListener(int, int, iv_requestlistener);
void SetRTLBook(int);
int SetSessionFlag(int, int, void *);
void SetShowPanelReader(int);
int SetSubtaskInfo(int, int, const char *, const char *);
int SetTaskParameters(int, const char *, const char *, struct ibitmap_s *, unsigned int);
void SetTextStrength(int);
void SetTrackPosition(int);
void SetTransparentColor(struct ibitmap_s **, int);
void SetUserAgent(int, const char *);
void SetVolume(int);
void SetWeakTimer(const char *, iv_timerproc, int);
void SetWeakTimerEx(const char *, iv_timerprocEx, void *, int);
void ShowHourglass();
void ShowHourglassAt(int, int);
void ShowHourglassForce();
void ShowHourglassForceAt(int, int);
void ShowPureHourglass();
void ShowPureHourglassForce();
void SoftUpdate();
void SoftUpdateHQ();
void StartPanelProgress(int, int);
int StartSoftwareUpdate();
void StopPanelProgress();
void Stretch(const unsigned char *, int, int, int, int, int, int, int, int, int);
void StretchArea(const unsigned char *, int, int, int, int, int, int, int, int, int, int, int);
void StretchAreaBW(const unsigned char *, int, int, int, int, int, int, int, int, int, int);
void StretchBitmap(int, int, int, int, const struct ibitmap_s *, int);
int StringWidth(const char *);
int StringWidthExt(const char *, int);
void SubtaskFinished(int);
void SwitchBookmark(int, long long int, int *, long long int *, int *, int, iv_bmkhandler);
int SwitchSubtask(int);
int TestCurrentApplicationAttribute(APPLICATION_ATTRIBUTE);
int TextRectHeight(int, const char *, int);
int TextRectHeightEx(int, int, const char *, int);
void TileBitmap(int, int, int, int, const struct ibitmap_s *);
void TogglePlaying();
void Transparent(int, int, int, int, int);
void TransparentRect(struct irect_s, int);
void trim_right(char *);
int ucs2utf(const unsigned short *, char *, int);
int unescape(const char *, char *, int);
int unlink_file_with_af(const char *);
void UnpackParameters(void *, int, int *, char ***);
void UpdateConfigPage(const char *, struct iconfigedit_s *);
void UpdateCurrentConfigPage();
void UpdateMenuEx(struct imenuex_s *);
int UpdateProgressbar(const char *, int);
int utf2ucs(const char *, unsigned short *, int);
int utf2ucs4(const char *, unsigned int *, int);
int utf_tolower_ext(char *, int, char **, int *);
int utf_toupper_ext(char *, int, char **, int *);
void vhash_add(struct ihash_s *, const char *, const void *);
void vhash_delete(struct ihash_s *, const char *);
const void *vhash_find(struct ihash_s *, const char *);
struct ihash_s *vhash_new(int, void *(*)(void *), iv_hashdelproc);
void WaitForUpdateComplete();
int WiFiPower(int);
struct wifi_ap_list_s *WiFiScanProcessGetResults(void);
void WiFiScanProcessSetSelectiveList(struct wifi_ap_list_s *);
int WiFiScanProcessStart(void);
int WiFiScanProcessStop(void);
char *wpa_passphrase(char *, char *);
void WriteInt(struct iconfig_s *, const char *, int);
void WriteIntVolatile(struct iconfig_s *, const char *, int);
void WriteSecret(struct iconfig_s *, const char *, const char *);
int WriteStartupLogo(const struct ibitmap_s *);
void WriteString(struct iconfig_s *, const char *, const char *);
void WriteStringVolatile(struct iconfig_s *, const char *, const char *);
struct ibitmap_s *zLoadBitmap(void *, const char *);
struct hw_event_data_pointer_s {
  int id;
  int x;
  int y;
  int pressure;
  enum input_dev_e devtype;
};
struct hw_event_data_common_s {
  int mod;
  int par1;
  int par2;
};
struct hw_event_s {
  int type;
  union {
    struct hw_event_data_common_s common;
    struct hw_event_data_pointer_s pointer;
  };
  struct timeval time;
};
typedef struct hw_event_s hw_event;
int hw_init();
void hw_close();
void hw_setglobalkeymask(long int, long int, long int);
void iv_setup_touchpanel();
void iv_setup_gsensor();
void iv_update_orientation(int);
int hw_get_keylock();
]])
